import pytest

from ml4setk import (
    CommentQuery,
    CommentSanitizer,
    LineCommentQuery,
    QueryMatch,
    sanitize_comment,
)

pytestmark = pytest.mark.unit


C_SHARP_STACK_V2_BLOCK_COMMENT = (
    "/*\n"
    " * Copyright 2018 JDCLOUD.COM\n"
    " *\n"
    ' * Licensed under the Apache License, Version 2.0 (the "License");\n'
    " * you may not use this file except in compliance with the License.\n"
    " * You may obtain a copy of the License at\n"
    " *\n"
    " *    http:#www.apache.org/licenses/LICENSE-2.0\n"
    " *\n"
    " * Unless required by applicable law or agreed to in writing, software\n"
    ' * distributed under the License is distributed on an "AS IS" BASIS,\n'
    " * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
    " * See the License for the specific language governing permissions and\n"
    " * limitations under the License.\n"
    " *\n"
    " * 媒体处理相关接口\n"
    " * 多媒体处理服务API，包括截图、转码、媒体处理消息通知等操作。"
    "本文档详细说明了媒体处理API及用法，适合开发人员阅读。\n"
    " *\n"
    " * OpenAPI spec version: v1\n"
    " * Contact: \n"
    " *\n"
    " * NOTE: This class is auto generated by the jdcloud code generator program.\n"
    " */"
)

C_SHARP_STACK_V2_SOURCE_SUFFIX = (
    "\n\n\n"
    "using System;\n"
    "using System.Collections.Generic;\n"
    "using System.Text;\n"
    "using JDCloudSDK.Core.Service;\n"
    "\n\n"
    "namespace  JDCloudSDK.Mps.Apis\n"
    "{\n"
    "\n"
    "    /// <summary>\n"
    "    ///  获取媒体处理通知\n"
    "    /// </summary>\n"
    "    public class GetNotificationResponse : JdcloudResponse<GetNotificationResult>\n"
    "    {\n"
    "    }\n"
    "}"
)

C_SHARP_STACK_V2_SOURCE = (
    C_SHARP_STACK_V2_BLOCK_COMMENT + C_SHARP_STACK_V2_SOURCE_SUFFIX
)

C_SHARP_STACK_V2_CLEANED_COMMENT = (
    "Copyright 2018 JDCLOUD.COM\n"
    "\n"
    'Licensed under the Apache License, Version 2.0 (the "License");\n'
    "you may not use this file except in compliance with the License.\n"
    "You may obtain a copy of the License at\n"
    "\n"
    "   http:#www.apache.org/licenses/LICENSE-2.0\n"
    "\n"
    "Unless required by applicable law or agreed to in writing, software\n"
    'distributed under the License is distributed on an "AS IS" BASIS,\n'
    "WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
    "See the License for the specific language governing permissions and\n"
    "limitations under the License.\n"
    "\n"
    "媒体处理相关接口\n"
    "多媒体处理服务API，包括截图、转码、媒体处理消息通知等操作。"
    "本文档详细说明了媒体处理API及用法，适合开发人员阅读。\n"
    "\n"
    "OpenAPI spec version: v1\n"
    "Contact:\n"
    "\n"
    "NOTE: This class is auto generated by the jdcloud code generator program."
)

C_SHARP_STACK_V2_AWS_LICENSE_BLOCK_COMMENT = (
    "/*\n"
    " * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.\n"
    " * \n"
    ' * Licensed under the Apache License, Version 2.0 (the "License").\n'
    " * You may not use this file except in compliance with the License.\n"
    " * A copy of the License is located at\n"
    " * \n"
    " *  http://aws.amazon.com/apache2.0\n"
    " * \n"
    ' * or in the "license" file accompanying this file. This file is distributed\n'
    ' * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either\n'
    " * express or implied. See the License for the specific language governing\n"
    " * permissions and limitations under the License.\n"
    " */"
)
C_SHARP_STACK_V2_AWS_LICENSE_MATCH_START = 0
C_SHARP_STACK_V2_AWS_LICENSE_MATCH_END = 577
C_SHARP_STACK_V2_AWS_LICENSE_MATCH_LINE = 1
C_SHARP_STACK_V2_AWS_LICENSE_MATCH_COLUMN = 1
C_SHARP_STACK_V2_AWS_LICENSE_SOURCE_SUFFIX = (
    "\n\n"
    "/*\n"
    " * Do not modify this file. This file is generated from the "
    "elasticache-2015-02-02.normal.json service model.\n"
    " */\n"
    "using System;\n"
    "using System.Collections.Generic;\n"
    "using System.Globalization;\n"
    "using System.IO;\n"
    "using System.Net;\n"
    "using System.Text;\n"
    "using System.Xml.Serialization;\n"
)
C_SHARP_STACK_V2_AWS_LICENSE_SOURCE = (
    C_SHARP_STACK_V2_AWS_LICENSE_BLOCK_COMMENT
    + C_SHARP_STACK_V2_AWS_LICENSE_SOURCE_SUFFIX
)
C_SHARP_STACK_V2_AWS_LICENSE_CLEANED_COMMENT = (
    "Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.\n"
    "\n"
    'Licensed under the Apache License, Version 2.0 (the "License").\n'
    "You may not use this file except in compliance with the License.\n"
    "A copy of the License is located at\n"
    "\n"
    " http://aws.amazon.com/apache2.0\n"
    "\n"
    'or in the "license" file accompanying this file. This file is distributed\n'
    'on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either\n'
    "express or implied. See the License for the specific language governing\n"
    "permissions and limitations under the License."
)

STACK_V2_INLINE_CSHARP_BLOCK_COMMENT = '/*Part.StartsWith("hd") || */'
STACK_V2_INLINE_CSHARP_CLEANED_COMMENT = 'Part.StartsWith("hd") ||'
STACK_V2_INLINE_CSHARP_MATCH_START = 39523
STACK_V2_INLINE_CSHARP_MATCH_END = 39552
STACK_V2_INLINE_CSHARP_MATCH_LINE = 1023
STACK_V2_INLINE_CSHARP_MATCH_COLUMN = 45
STACK_V2_INLINE_CSHARP_LINE_PREFIX = "                                        if ("
STACK_V2_INLINE_CSHARP_SOURCE_SUFFIX = (
    'Part.StartsWith("sh") || Part.StartsWith("cp") || '
    'Part.StartsWith("cc") || Part.StartsWith("ch") || '
    'Part.StartsWith("lg") || Part.StartsWith("ca") || '
    'Part.StartsWith("wa"))\n'
    "                                            continue;\n"
)

STACK_V2_CSHARP_CONDITION_PRIORITY_BLOCK_COMMENT = (
    "/*(destinationEntry.conditionPriority == priority) ||*/"
)
STACK_V2_CSHARP_CONDITION_PRIORITY_CLEANED_COMMENT = (
    "(destinationEntry.conditionPriority == priority) ||"
)
STACK_V2_CSHARP_CONDITION_PRIORITY_MATCH_START = 19661
STACK_V2_CSHARP_CONDITION_PRIORITY_MATCH_END = 19716
STACK_V2_CSHARP_CONDITION_PRIORITY_MATCH_LINE = 381
STACK_V2_CSHARP_CONDITION_PRIORITY_MATCH_COLUMN = 56
STACK_V2_CSHARP_CONDITION_PRIORITY_LINE_PREFIX = (
    "                    if ((destinationEntry != null) && ("
)
STACK_V2_CSHARP_CONDITION_PRIORITY_SOURCE_SUFFIX = (
    " (link.priority == priority))) // Note: Only observe link priority. "
    "Why does Chat Mapper even have conditionPriority?\n"
    "                    {\n"
    "                        CharacterType characterType = "
    "m_database.GetCharacterType(destinationEntry.ActorID);\n"
)

STACK_V2_CSHARP_COOKIE_BLOCK_COMMENT = "/* createPersistentCookie */"
STACK_V2_CSHARP_COOKIE_CLEANED_COMMENT = "createPersistentCookie"
STACK_V2_CSHARP_COOKIE_MATCH_START = 3127
STACK_V2_CSHARP_COOKIE_MATCH_END = 3155
STACK_V2_CSHARP_COOKIE_MATCH_LINE = 97
STACK_V2_CSHARP_COOKIE_MATCH_COLUMN = 63
STACK_V2_CSHARP_COOKIE_DUPLICATE_START = 3031
STACK_V2_CSHARP_COOKIE_LINE_PREFIX = (
    "                    FormsService.SignIn(model.UserName, false "
)
STACK_V2_CSHARP_COOKIE_SOURCE_SUFFIX = (
    ");\r\n"
    '                    return RedirectToAction("Index", "Home");\r\n'
)

STACK_V2_CSHARP_ORNAMENT_BLOCK_COMMENT = "/* Script Made By Daniel */"
STACK_V2_CSHARP_ORNAMENT_CLEANED_COMMENT = "Script Made By Daniel"
STACK_V2_CSHARP_ORNAMENT_MATCH_START = 157
STACK_V2_CSHARP_ORNAMENT_MATCH_END = 184
STACK_V2_CSHARP_ORNAMENT_MATCH_LINE = 5
STACK_V2_CSHARP_ORNAMENT_MATCH_COLUMN = 1
STACK_V2_CSHARP_ORNAMENT_SOURCE_PREFIX = (
    "\ufeffusing UnityEngine;\n\n"
    "public enum OrnamentType { Candle, Flower, Statue, Heart, "
    "[System.ObsoleteAttribute] NumberOfTypes, "
    "[System.ObsoleteAttribute] None };\n\n"
)
STACK_V2_CSHARP_ORNAMENT_SOURCE_SUFFIX = (
    "\n"
    "public class Ornament : PlaceablePickup\n"
    "{\n"
    "    #region Variables\n"
    '    [Header("Ornament")]\n'
    "    [SerializeField] private OrnamentType ornamentType;\n"
    "    #endregion\n"
    "\n"
    "    public OrnamentType GetOrnamentType() { return ornamentType; }\n"
    "\n"
    "    public void ReturnToPool(bool skipRemoveFromList = false)\n"
    "    {\n"
    "        ExecuteParticle();\n"
    "        AudioManager.GetInstance().PlaySoundAtPosition(despawnClip, transform);\n"
    "        if (ActiveHand) ActiveHand.Drop();\n"
    "        if (Placement) Placement.RemovePlacedObject();\n"
    "        PoolManager.ReturnOrnament(this, skipRemoveFromList);\n"
    "    }\n"
    "}"
)
STACK_V2_CSHARP_ORNAMENT_SOURCE = (
    STACK_V2_CSHARP_ORNAMENT_SOURCE_PREFIX
    + STACK_V2_CSHARP_ORNAMENT_BLOCK_COMMENT
    + STACK_V2_CSHARP_ORNAMENT_SOURCE_SUFFIX
)

C_SHARP_STACK_V2_DECORATED_METADATA_BLOCK_COMMENT = (
    "/**\n"
    " * =================================\n"
    " * 作    者:\n"
    " * 创建日期：2015/9/6\n"
    " * 描    述：\n"
    " * \n"
    " * =================================\n"
    " * */"
)
C_SHARP_STACK_V2_DECORATED_METADATA_MATCH_START = 1
C_SHARP_STACK_V2_DECORATED_METADATA_MATCH_END = 127
C_SHARP_STACK_V2_DECORATED_METADATA_MATCH_LINE = 2
C_SHARP_STACK_V2_DECORATED_METADATA_MATCH_COLUMN = 1
C_SHARP_STACK_V2_DECORATED_METADATA_SOURCE_SUFFIX = (
    "\n"
    "using System;\n"
    "using System.Collections.Generic;\n"
    "using System.Linq;\n"
    "using System.Text;\n"
    "using iSinta.House.Domain.Domain.Basic;\n"
    "using iSinta.House.Domain.Domain.TaskModel;\n"
    "\n"
    "namespace iSinta.House.Domain.Contracts.Tasks.Basic\n"
    "{\n"
    "    public interface IBaseCityTask\n"
    "    {\n"
    "        /// <summary>\n"
    "        /// 创建数据\n"
    "        /// </summary>\n"
    "        int AddBaseCity(BaseCity basecity);\n"
    "    }\n"
    "}\n"
)
C_SHARP_STACK_V2_DECORATED_METADATA_CLEANED_COMMENT = (
    "=================================\n"
    "作    者:\n"
    "创建日期：2015/9/6\n"
    "描    述：\n"
    "\n"
    "================================="
)

C_SHARP_STACK_V2_RECTANGLE_BLOCK_COMMENT = (
    "/*Написать программу, которая определяет площадь прямоугольника \n"
    "со сторонами a и b.Если пользователь вводит некорректные значения \n"
    "(отрицательные, или 0), должно выдаваться сообщение об ошибке.\n"
    "Возможность ввода пользователем строки вида «абвгд», или нецелых \n"
    "чисел игнорировать.*/"
)
C_SHARP_STACK_V2_RECTANGLE_MATCH_START = 1
C_SHARP_STACK_V2_RECTANGLE_MATCH_END = 283
C_SHARP_STACK_V2_RECTANGLE_MATCH_LINE = 1
C_SHARP_STACK_V2_RECTANGLE_MATCH_COLUMN = 2
C_SHARP_STACK_V2_RECTANGLE_SOURCE_PREFIX = "\ufeff"
C_SHARP_STACK_V2_RECTANGLE_SOURCE_SUFFIX = (
    "\n\n"
    "namespace Task01\n"
    "{\n"
    "    using System;\n"
    "\n"
    "    internal class Program\n"
    "    {\n"
    "        private static void Main(string[] args)\n"
    "        {\n"
    '            Console.Write("Enter a : ");\n'
    "            double a = double.Parse(Console.ReadLine());//todo pn возможна "
    "исключительная ситуация\n"
    "\t\t\twhile (a <= 0)\n"
    "            {\n"
    '                Console.WriteLine("Error! Try again: ");\n'
    "                a = double.Parse(Console.ReadLine());//todo pn возможна "
    "исключительная ситуация\n"
    "\t\t\t}\n"
    "\n"
    '            Console.Write("Enter b: ");\n'
    "            double b = double.Parse(Console.ReadLine());//todo pn возможна "
    "исключительная ситуация\n"
    "\t\t\twhile (b <= 0)\n"
    "            {\n"
    '                Console.WriteLine("Error! Try again: ");\n'
    "                b = double.Parse(Console.ReadLine());//todo pn возможна "
    "исключительная ситуация\n"
    "\t\t\t}\n"
    "\n"
    "            AreaOfRectangle area = new AreaOfRectangle();\n"
    "            area.FindAreaOfRectangle(a, b);\n"
    "        }\n"
    "    }\n"
    "}\n"
)
C_SHARP_STACK_V2_RECTANGLE_SOURCE = (
    C_SHARP_STACK_V2_RECTANGLE_SOURCE_PREFIX
    + C_SHARP_STACK_V2_RECTANGLE_BLOCK_COMMENT
    + C_SHARP_STACK_V2_RECTANGLE_SOURCE_SUFFIX
)
C_SHARP_STACK_V2_RECTANGLE_CLEANED_COMMENT = (
    "Написать программу, которая определяет площадь прямоугольника\n"
    "со сторонами a и b.Если пользователь вводит некорректные значения\n"
    "(отрицательные, или 0), должно выдаваться сообщение об ошибке.\n"
    "Возможность ввода пользователем строки вида «абвгд», или нецелых\n"
    "чисел игнорировать."
)

C_SHARP_STACK_V2_PERLIN_BLOCK_COMMENT = (
    "/* Perlin noise class.  ( by Tom Nuydens (tom@delphi3d.net) )\r\n"
    "* Converted to C# by Mattias Fagerlund, Mattias.Fagerlund@cortego.se\r\n"
    "\r\n"
    "******************************************************************************\r\n"
    "\r\n"
    "I used the following references for my implementation:\r\n"
    " http://students.vassar.edu/mazucker/code/perlin-noise-math-faq.html\r\n"
    ' Darwin Peachey\'s chapter in "Texturing & Modeling: A Procedural Approach"\r\n'
    "Another good resource is\r\n"
    " http://freespace.virgin.net/hugo.elias/models/m_perlin.htm\r\n"
    "\r\n"
    "******************************************************************************\r\n"
    "\r\n"
    "This class generates 3D Perlin noise. The demo that comes with this is 2D, but\r\n"
    "uses the 3rd dimension to create animated noise. The noise does not tile,\r\n"
    "although it could be made to do so with a few small modifications to the\r\n"
    "algorithm.\r\n"
    "\r\n"
    "Perlin noise can be used as a starting point for all kinds of things,\r\n"
    "including terrain generation, cloud rendering, procedural textures, and more.\r\n"
    'Most of these techniques involve rendering multiple "octaves" of noise. This\r\n'
    "means you generate multiple noise values for every pixel (each with different\r\n"
    "X, Y and/or Z coordinates), and then sum them. There's an example of this in\r\n"
    "the accompanying demo.\r\n"
    "*/"
)
C_SHARP_STACK_V2_PERLIN_MATCH_START = 127
C_SHARP_STACK_V2_PERLIN_MATCH_END = 1371
C_SHARP_STACK_V2_PERLIN_MATCH_LINE = 9
C_SHARP_STACK_V2_PERLIN_MATCH_COLUMN = 9
C_SHARP_STACK_V2_PERLIN_SOURCE_PREFIX = (
    "\ufeffusing System;\r\n"
    "using System.Collections.Generic;\r\n"
    "using System.Linq;\r\n"
    "using System.Text;\r\n"
    "\r\n"
    "namespace HeartGame\r\n"
    "{\r\n"
    "\r\n"
    "        "
)
C_SHARP_STACK_V2_PERLIN_SOURCE_SUFFIX = (
    "\r\n"
    "\r\n"
    "    public class Perlin\r\n"
    "    {\r\n"
    "\r\n"
    "        public Perlin(int seed)\r\n"
    "        {\r\n"
    "            Random rand = new Random(seed);\r\n"
    "            shufflepermutation(rand);\r\n"
    "        }\r\n"
    "    }\r\n"
    "}\r\n"
)
C_SHARP_STACK_V2_PERLIN_SOURCE = (
    C_SHARP_STACK_V2_PERLIN_SOURCE_PREFIX
    + C_SHARP_STACK_V2_PERLIN_BLOCK_COMMENT
    + C_SHARP_STACK_V2_PERLIN_SOURCE_SUFFIX
)
C_SHARP_STACK_V2_PERLIN_CLEANED_COMMENT = (
    " Perlin noise class.  ( by Tom Nuydens (tom@delphi3d.net) )\n"
    "* Converted to C# by Mattias Fagerlund, Mattias.Fagerlund@cortego.se\n"
    "\n"
    "******************************************************************************\n"
    "\n"
    "I used the following references for my implementation:\n"
    " http://students.vassar.edu/mazucker/code/perlin-noise-math-faq.html\n"
    ' Darwin Peachey\'s chapter in "Texturing & Modeling: A Procedural Approach"\n'
    "Another good resource is\n"
    " http://freespace.virgin.net/hugo.elias/models/m_perlin.htm\n"
    "\n"
    "******************************************************************************\n"
    "\n"
    "This class generates 3D Perlin noise. The demo that comes with this is 2D, but\n"
    "uses the 3rd dimension to create animated noise. The noise does not tile,\n"
    "although it could be made to do so with a few small modifications to the\n"
    "algorithm.\n"
    "\n"
    "Perlin noise can be used as a starting point for all kinds of things,\n"
    "including terrain generation, cloud rendering, procedural textures, and more.\n"
    'Most of these techniques involve rendering multiple "octaves" of noise. This\n'
    "means you generate multiple noise values for every pixel (each with different\n"
    "X, Y and/or Z coordinates), and then sum them. There's an example of this in\n"
    "the accompanying demo."
)

C_SHARP_STACK_V2_CGSOSO_BLOCK_COMMENT = (
    "/*\r\n"
    "http://www.cgsoso.com/forum-211-1.html\r\n"
    "\r\n"
    "CG搜搜 Unity3d 每日Unity3d插件免费更新 更有VIP资源！\r\n"
    "\r\n"
    "CGSOSO 主打游戏开发，影视设计等CG资源素材。\r\n"
    "\r\n"
    "插件如若商用，请务必官网购买！\r\n"
    "\r\n"
    "daily assets update for try.\r\n"
    "\r\n"
    "U should buy the asset from home store if u use it in your project!\r\n"
    "*/"
)
C_SHARP_STACK_V2_CGSOSO_MATCH_START = 0
C_SHARP_STACK_V2_CGSOSO_MATCH_END = 239
C_SHARP_STACK_V2_CGSOSO_MATCH_LINE = 1
C_SHARP_STACK_V2_CGSOSO_MATCH_COLUMN = 1
C_SHARP_STACK_V2_CGSOSO_SOURCE_SUFFIX = (
    "\r\n"
    "\r\n"
    "using System;\r\n"
    "\r\n"
    "namespace GoogleMobileAds.Api\r\n"
    "{\r\n"
    "    public interface IInAppPurchaseResult\r\n"
    "    {\r\n"
    "        void FinishPurchase();\r\n"
    "        string ProductId { get; }\r\n"
    "    }\r\n"
    "}\r\n"
)
C_SHARP_STACK_V2_CGSOSO_SOURCE = (
    C_SHARP_STACK_V2_CGSOSO_BLOCK_COMMENT
    + C_SHARP_STACK_V2_CGSOSO_SOURCE_SUFFIX
)
C_SHARP_STACK_V2_CGSOSO_CLEANED_COMMENT = (
    "http://www.cgsoso.com/forum-211-1.html\n"
    "\n"
    "CG搜搜 Unity3d 每日Unity3d插件免费更新 更有VIP资源！\n"
    "\n"
    "CGSOSO 主打游戏开发，影视设计等CG资源素材。\n"
    "\n"
    "插件如若商用，请务必官网购买！\n"
    "\n"
    "daily assets update for try.\n"
    "\n"
    "U should buy the asset from home store if u use it in your project!"
)

C_SHARP_STACK_V2_INTERACTION_TODO_LINE_COMMENT = (
    "//TODO this needs a lot of refractoring, a lot of duped code\n"
    "//TODO This belongs somewhere else I think maybe on the Object Base class"
)
C_SHARP_STACK_V2_INTERACTION_TODO_CLEANED_COMMENT = (
    "TODO this needs a lot of refractoring, a lot of duped code\n"
    "TODO This belongs somewhere else I think maybe on the Object Base class"
)
C_SHARP_STACK_V2_INTERACTION_TODO_MATCH_START = 94
C_SHARP_STACK_V2_INTERACTION_TODO_MATCH_END = 228
C_SHARP_STACK_V2_INTERACTION_TODO_MATCH_LINE = 6
C_SHARP_STACK_V2_INTERACTION_TODO_MATCH_COLUMN = 1
C_SHARP_STACK_V2_INTERACTION_TODO_SOURCE_PREFIX = (
    "using System;\n"
    "using System.Collections;\n"
    "using System.Collections.Generic;\n"
    "using UnityEngine;\n"
    "\n"
)
C_SHARP_STACK_V2_INTERACTION_TODO_SOURCE_SUFFIX = (
    "\n"
    "public enum Interaction {\n"
    "    Unscrew,\n"
    "    Screw,\n"
    "}\n"
)
C_SHARP_STACK_V2_INTERACTION_TODO_SOURCE = (
    C_SHARP_STACK_V2_INTERACTION_TODO_SOURCE_PREFIX
    + C_SHARP_STACK_V2_INTERACTION_TODO_LINE_COMMENT
    + C_SHARP_STACK_V2_INTERACTION_TODO_SOURCE_SUFFIX
)

C_SHARP_STACK_V2_STARTUP_LINE_COMMENT = (
    "// This method gets called by the runtime. Use this method to add services "
    "to the container.\n"
    "        // For more information on how to configure your application, visit "
    "http://go.microsoft.com/fwlink/?LinkID=398940"
)
C_SHARP_STACK_V2_STARTUP_MATCH_START = 994
C_SHARP_STACK_V2_STARTUP_MATCH_END = 1208
C_SHARP_STACK_V2_STARTUP_MATCH_LINE = 30
C_SHARP_STACK_V2_STARTUP_MATCH_COLUMN = 9
C_SHARP_STACK_V2_STARTUP_SOURCE_PREFIX = (
    "\ufeffusing System;\n"
    "using System.Collections.Generic;\n"
    "using System.Linq;\n"
    "using System.Threading.Tasks;\n"
    "using Microsoft.AspNetCore.Builder;\n"
    "using Microsoft.AspNetCore.Hosting;\n"
    "using Microsoft.AspNetCore.Http;\n"
    "using Microsoft.Extensions.DependencyInjection;\n"
    "using Microsoft.Extensions.Logging;\n"
    "using Microsoft.Extensions.Configuration;\n"
    "using ExploreCalifornia.Models;\n"
    "using Microsoft.EntityFrameworkCore;\n"
    "using Microsoft.AspNetCore.Identity.EntityFrameworkCore;\n"
    "\n"
    "namespace ExploreCalifornia\n"
    "{\n"
    "    public class Startup\n"
    "    {\n"
    "        private readonly IConfigurationRoot configuration;\n"
    "\n"
    "        public Startup(IHostingEnvironment env)\n"
    "        {\n"
    "            configuration = new ConfigurationBuilder()\n"
    "                                .AddEnvironmentVariables()\n"
    '                                .AddJsonFile(env.ContentRootPath + "/config.json")\n'
    "                                .AddJsonFile(env.ContentRootPath + "
    '"/config.development.json", true)\n'
    "                                .Build();\n"
    "        }\n"
    "\n"
    "        "
)
C_SHARP_STACK_V2_STARTUP_SOURCE_SUFFIX = (
    "\n"
    "        public void ConfigureServices(IServiceCollection services)\n"
    "        {\n"
    "            \n"
    "            services.AddTransient<FormattingService>();\n"
    "        }\n"
    "    }\n"
    "}\n"
)
C_SHARP_STACK_V2_STARTUP_SOURCE = (
    C_SHARP_STACK_V2_STARTUP_SOURCE_PREFIX
    + C_SHARP_STACK_V2_STARTUP_LINE_COMMENT
    + C_SHARP_STACK_V2_STARTUP_SOURCE_SUFFIX
)
C_SHARP_STACK_V2_STARTUP_CLEANED_COMMENT = (
    "This method gets called by the runtime. Use this method to add services "
    "to the container.\n"
    "For more information on how to configure your application, visit "
    "http://go.microsoft.com/fwlink/?LinkID=398940"
)

C_SHARP_STACK_V2_NOVARTIS_LINE_COMMENT = (
    "/////////////////////////////////////////////////////////////////////////////////\n"
    "//\n"
    "// © 2010 Novartis AG. All rights reserved.\n"
    "//\n"
    "// These coded instructions, statements and computer programs contain unpublished\n"
    "// proprietary information of Novartis AG and are protected by federal  copyright\n"
    "// law. They may not be disclosed to third parties or copied or duplicated in any\n"
    "// form, in whole or in part, without the prior written consent of Novartis AG.\n"
    "//\n"
    "// Author: Bernhard Rode, wega Informatik AG\n"
    "//\n"
    "/////////////////////////////////////////////////////////////////////////////////"
)
C_SHARP_STACK_V2_NOVARTIS_CLEANED_COMMENT = (
    "© 2010 Novartis AG. All rights reserved.\n"
    "\n"
    "These coded instructions, statements and computer programs contain unpublished\n"
    "proprietary information of Novartis AG and are protected by federal  copyright\n"
    "law. They may not be disclosed to third parties or copied or duplicated in any\n"
    "form, in whole or in part, without the prior written consent of Novartis AG.\n"
    "\n"
    "Author: Bernhard Rode, wega Informatik AG"
)
C_SHARP_STACK_V2_NOVARTIS_MATCH_START = 38
C_SHARP_STACK_V2_NOVARTIS_MATCH_END = 628
C_SHARP_STACK_V2_NOVARTIS_MATCH_LINE = 2
C_SHARP_STACK_V2_NOVARTIS_MATCH_COLUMN = 1
C_SHARP_STACK_V2_NOVARTIS_SOURCE_PREFIX = (
    "\ufeff#region Copyright © 2010 Novartis AG\n"
)
C_SHARP_STACK_V2_NOVARTIS_SOURCE_SUFFIX = (
    "\n"
    "#endregion Copyright © 2010 Novartis AG\n"
    "\n"
    "using System.Reflection;\n"
    "using System.Runtime.CompilerServices;\n"
    "using System.Runtime.InteropServices;\n"
    "\n"
    '[assembly: AssemblyTitle("WiffLoader")]\n'
)
C_SHARP_STACK_V2_NOVARTIS_SOURCE = (
    C_SHARP_STACK_V2_NOVARTIS_SOURCE_PREFIX
    + C_SHARP_STACK_V2_NOVARTIS_LINE_COMMENT
    + C_SHARP_STACK_V2_NOVARTIS_SOURCE_SUFFIX
)

C_SHARP_STACK_V2_SOCKET_XML_DOC_LINE_COMMENT = (
    "/// <summary>\n"
    "    /// 单点采集器GPRS通讯对象\n"
    "    /// </summary>"
)
C_SHARP_STACK_V2_SOCKET_XML_DOC_CLEANED_COMMENT = (
    "<summary>\n"
    "单点采集器GPRS通讯对象\n"
    "</summary>"
)
C_SHARP_STACK_V2_SOCKET_XML_DOC_MATCH_START = 347
C_SHARP_STACK_V2_SOCKET_XML_DOC_MATCH_END = 401
C_SHARP_STACK_V2_SOCKET_XML_DOC_MATCH_LINE = 15
C_SHARP_STACK_V2_SOCKET_XML_DOC_MATCH_COLUMN = 5
C_SHARP_STACK_V2_SOCKET_XML_DOC_SOURCE_PREFIX = (
    "\ufeffusing JYGCloud.JOBMonitor.Common;\n"
    "using JYGCloud.JOBMonitor.ICommunicate;\n"
    "using System;\n"
    "using System.Collections.Generic;\n"
    "using System.Linq;\n"
    "using System.Net;\n"
    "using System.Net.Sockets;\n"
    "using System.Runtime.CompilerServices;\n"
    "using System.Text;\n"
    "using System.Threading;\n"
    "using System.Threading.Tasks;\n"
    "\n"
    "namespace JYGCloud.JOBMonitor.Communicate\n"
    "{\n"
    "    "
)
C_SHARP_STACK_V2_SOCKET_XML_DOC_SOURCE_SUFFIX = (
    "\n"
    "    public sealed class SCMGPRSCommunicate : IBaseCommunicate<string>\n"
    "    {\n"
    "    }\n"
    "}\n"
)
C_SHARP_STACK_V2_SOCKET_XML_DOC_SOURCE = (
    C_SHARP_STACK_V2_SOCKET_XML_DOC_SOURCE_PREFIX
    + C_SHARP_STACK_V2_SOCKET_XML_DOC_LINE_COMMENT
    + C_SHARP_STACK_V2_SOCKET_XML_DOC_SOURCE_SUFFIX
)


def _stack_v2_positioned_prefix(match_start, match_line, match_column, line_prefix):
    """Build a synthetic prefix with the reported Stack v2 location metadata.

    Args:
        match_start: Zero-based character offset where the comment starts.
        match_line: One-based line number where the comment starts.
        match_column: One-based column where the comment starts.
        line_prefix: Text before the comment on the target line.

    Returns:
        Source text that places the next character at the requested location.
    """

    assert len(line_prefix) == match_column - 1
    previous_line_count = match_line - 1
    prefix_before_target_line_length = match_start - len(line_prefix)
    filler_body_length = prefix_before_target_line_length - previous_line_count
    base_line_length, longer_line_count = divmod(
        filler_body_length, previous_line_count
    )
    filler_lines = [
        "x" * (base_line_length + (1 if index < longer_line_count else 0))
        for index in range(previous_line_count)
    ]
    prefix = "\n".join(filler_lines) + "\n" + line_prefix

    assert len(prefix) == match_start
    assert prefix.count("\n") == previous_line_count
    return prefix


def _stack_v2_positioned_prefix_with_duplicate(
    match_start,
    match_line,
    match_column,
    line_prefix,
    duplicate_start,
    duplicate_comment,
):
    """Build a CRLF prefix that preserves an earlier duplicate comment.

    Args:
        match_start: Zero-based offset where the target comment starts.
        match_line: One-based line number where the target comment starts.
        match_column: One-based column where the target comment starts.
        line_prefix: Text before the target comment on its line.
        duplicate_start: Zero-based offset for an earlier duplicate comment.
        duplicate_comment: Raw duplicate comment text to place before target.

    Returns:
        Source text that places the next character at the target location and
        includes ``duplicate_comment`` at ``duplicate_start``.
    """

    assert len(line_prefix) == match_column - 1
    previous_line_count = match_line - 1
    target_line_start = match_start - len(line_prefix)
    leading_lines = "x\r\n" * (previous_line_count - 1)
    final_line_length = target_line_start - len(leading_lines) - len("\r\n")
    duplicate_line_offset = duplicate_start - len(leading_lines)
    final_line_after_duplicate_length = (
        final_line_length - duplicate_line_offset - len(duplicate_comment)
    )

    assert duplicate_line_offset >= 0
    assert final_line_after_duplicate_length >= 0

    final_line = (
        ("x" * duplicate_line_offset)
        + duplicate_comment
        + ("x" * final_line_after_duplicate_length)
    )
    prefix = leading_lines + final_line + "\r\n" + line_prefix

    assert len(prefix) == match_start
    assert prefix.count("\n") == previous_line_count
    assert prefix.find(duplicate_comment) == duplicate_start
    return prefix


def _query_match_location(match):
    """Return Stack v2-style start, end, line, and column for a query match.

    Args:
        match: Query match whose prefix and match text identify the location.

    Returns:
        Tuple of zero-based start, zero-based end, one-based line, and
        one-based column.
    """

    start = len(match.prefix)
    end = start + len(match.match)
    line = match.prefix.count("\n") + 1
    last_line_break = match.prefix.rfind("\n")
    column = start + 1 if last_line_break == -1 else start - last_line_break
    return start, end, line, column


def test_stack_v2_csharp_block_header_extracts_full_comment_with_offsets():
    matches = CommentQuery("c#").parse(C_SHARP_STACK_V2_SOURCE)

    target = matches[0]
    start = len(target.prefix)
    end = start + len(target.match)
    line = target.prefix.count("\n") + 1
    last_line_break = target.prefix.rfind("\n")
    column = start + 1 if last_line_break == -1 else start - last_line_break

    assert target == QueryMatch(
        "",
        C_SHARP_STACK_V2_SOURCE_SUFFIX,
        C_SHARP_STACK_V2_BLOCK_COMMENT,
    )
    assert (start, end, line, column) == (0, 794, 1, 1)


def test_stack_v2_csharp_block_header_sanitizes_gutters_and_preserves_content():
    target = QueryMatch(
        "",
        C_SHARP_STACK_V2_SOURCE_SUFFIX,
        C_SHARP_STACK_V2_BLOCK_COMMENT,
    )

    assert (
        CommentSanitizer("c#").sanitize(target) == C_SHARP_STACK_V2_CLEANED_COMMENT
    )
    assert (
        sanitize_comment("c#", C_SHARP_STACK_V2_BLOCK_COMMENT)
        == C_SHARP_STACK_V2_CLEANED_COMMENT
    )


def test_stack_v2_csharp_aws_license_header_extracts_full_comment_with_offsets():
    matches = CommentQuery("c#").parse(C_SHARP_STACK_V2_AWS_LICENSE_SOURCE)

    assert matches
    target = matches[0]

    assert target == QueryMatch(
        "",
        C_SHARP_STACK_V2_AWS_LICENSE_SOURCE_SUFFIX,
        C_SHARP_STACK_V2_AWS_LICENSE_BLOCK_COMMENT,
    )
    assert _query_match_location(target) == (
        C_SHARP_STACK_V2_AWS_LICENSE_MATCH_START,
        C_SHARP_STACK_V2_AWS_LICENSE_MATCH_END,
        C_SHARP_STACK_V2_AWS_LICENSE_MATCH_LINE,
        C_SHARP_STACK_V2_AWS_LICENSE_MATCH_COLUMN,
    )


def test_stack_v2_csharp_aws_license_header_sanitizes_gutters_and_blank_lines():
    target = QueryMatch("", "", C_SHARP_STACK_V2_AWS_LICENSE_BLOCK_COMMENT)

    assert (
        CommentSanitizer("c#").sanitize(target)
        == C_SHARP_STACK_V2_AWS_LICENSE_CLEANED_COMMENT
    )
    assert (
        sanitize_comment("c#", C_SHARP_STACK_V2_AWS_LICENSE_BLOCK_COMMENT)
        == C_SHARP_STACK_V2_AWS_LICENSE_CLEANED_COMMENT
    )


def test_stack_v2_csharp_inline_condition_block_extracts_full_comment_with_offsets():
    prefix = _stack_v2_positioned_prefix(
        STACK_V2_INLINE_CSHARP_MATCH_START,
        STACK_V2_INLINE_CSHARP_MATCH_LINE,
        STACK_V2_INLINE_CSHARP_MATCH_COLUMN,
        STACK_V2_INLINE_CSHARP_LINE_PREFIX,
    )
    source = (
        prefix
        + STACK_V2_INLINE_CSHARP_BLOCK_COMMENT
        + STACK_V2_INLINE_CSHARP_SOURCE_SUFFIX
    )

    matches = CommentQuery("c#").parse(source)

    assert matches
    target = matches[0]
    start = len(target.prefix)
    end = start + len(target.match)
    line = target.prefix.count("\n") + 1
    last_line_break = target.prefix.rfind("\n")
    column = start + 1 if last_line_break == -1 else start - last_line_break

    assert target == QueryMatch(
        prefix,
        STACK_V2_INLINE_CSHARP_SOURCE_SUFFIX,
        STACK_V2_INLINE_CSHARP_BLOCK_COMMENT,
    )
    assert (start, end, line, column) == (
        STACK_V2_INLINE_CSHARP_MATCH_START,
        STACK_V2_INLINE_CSHARP_MATCH_END,
        STACK_V2_INLINE_CSHARP_MATCH_LINE,
        STACK_V2_INLINE_CSHARP_MATCH_COLUMN,
    )


def test_stack_v2_csharp_inline_condition_block_sanitizes_code_like_content():
    target = QueryMatch("", "", STACK_V2_INLINE_CSHARP_BLOCK_COMMENT)

    assert (
        CommentSanitizer("c#").sanitize(target)
        == STACK_V2_INLINE_CSHARP_CLEANED_COMMENT
    )
    assert (
        sanitize_comment("c#", STACK_V2_INLINE_CSHARP_BLOCK_COMMENT)
        == STACK_V2_INLINE_CSHARP_CLEANED_COMMENT
    )


def test_stack_v2_csharp_condition_priority_block_extracts_full_comment_with_offsets():
    prefix = _stack_v2_positioned_prefix(
        STACK_V2_CSHARP_CONDITION_PRIORITY_MATCH_START,
        STACK_V2_CSHARP_CONDITION_PRIORITY_MATCH_LINE,
        STACK_V2_CSHARP_CONDITION_PRIORITY_MATCH_COLUMN,
        STACK_V2_CSHARP_CONDITION_PRIORITY_LINE_PREFIX,
    )
    source = (
        prefix
        + STACK_V2_CSHARP_CONDITION_PRIORITY_BLOCK_COMMENT
        + STACK_V2_CSHARP_CONDITION_PRIORITY_SOURCE_SUFFIX
    )

    matches = CommentQuery("c#").parse(source)

    assert matches
    target = matches[0]

    assert target == QueryMatch(
        prefix,
        STACK_V2_CSHARP_CONDITION_PRIORITY_SOURCE_SUFFIX,
        STACK_V2_CSHARP_CONDITION_PRIORITY_BLOCK_COMMENT,
    )
    assert _query_match_location(target) == (
        STACK_V2_CSHARP_CONDITION_PRIORITY_MATCH_START,
        STACK_V2_CSHARP_CONDITION_PRIORITY_MATCH_END,
        STACK_V2_CSHARP_CONDITION_PRIORITY_MATCH_LINE,
        STACK_V2_CSHARP_CONDITION_PRIORITY_MATCH_COLUMN,
    )


def test_stack_v2_csharp_condition_priority_block_sanitizes_code_like_content():
    target = QueryMatch("", "", STACK_V2_CSHARP_CONDITION_PRIORITY_BLOCK_COMMENT)

    assert (
        CommentSanitizer("c#").sanitize(target)
        == STACK_V2_CSHARP_CONDITION_PRIORITY_CLEANED_COMMENT
    )
    assert (
        sanitize_comment("c#", STACK_V2_CSHARP_CONDITION_PRIORITY_BLOCK_COMMENT)
        == STACK_V2_CSHARP_CONDITION_PRIORITY_CLEANED_COMMENT
    )


def test_stack_v2_csharp_duplicate_cookie_block_extracts_target_with_offsets():
    prefix = _stack_v2_positioned_prefix_with_duplicate(
        STACK_V2_CSHARP_COOKIE_MATCH_START,
        STACK_V2_CSHARP_COOKIE_MATCH_LINE,
        STACK_V2_CSHARP_COOKIE_MATCH_COLUMN,
        STACK_V2_CSHARP_COOKIE_LINE_PREFIX,
        STACK_V2_CSHARP_COOKIE_DUPLICATE_START,
        STACK_V2_CSHARP_COOKIE_BLOCK_COMMENT,
    )
    source = (
        prefix
        + STACK_V2_CSHARP_COOKIE_BLOCK_COMMENT
        + STACK_V2_CSHARP_COOKIE_SOURCE_SUFFIX
    )

    matches = CommentQuery("c#").parse(source)

    cookie_matches = [
        match for match in matches if match.match == STACK_V2_CSHARP_COOKIE_BLOCK_COMMENT
    ]
    cookie_starts = [len(match.prefix) for match in cookie_matches]

    assert cookie_starts == [
        STACK_V2_CSHARP_COOKIE_DUPLICATE_START,
        STACK_V2_CSHARP_COOKIE_MATCH_START,
    ]

    target = cookie_matches[-1]
    start = len(target.prefix)
    end = start + len(target.match)
    line = target.prefix.count("\n") + 1
    last_line_break = target.prefix.rfind("\n")
    column = start + 1 if last_line_break == -1 else start - last_line_break

    assert target == QueryMatch(
        prefix,
        STACK_V2_CSHARP_COOKIE_SOURCE_SUFFIX,
        STACK_V2_CSHARP_COOKIE_BLOCK_COMMENT,
    )
    assert (start, end, line, column) == (
        STACK_V2_CSHARP_COOKIE_MATCH_START,
        STACK_V2_CSHARP_COOKIE_MATCH_END,
        STACK_V2_CSHARP_COOKIE_MATCH_LINE,
        STACK_V2_CSHARP_COOKIE_MATCH_COLUMN,
    )


def test_stack_v2_csharp_duplicate_cookie_block_sanitizes_identifier_content():
    target = QueryMatch("", "", STACK_V2_CSHARP_COOKIE_BLOCK_COMMENT)

    assert (
        CommentSanitizer("c#").sanitize(target)
        == STACK_V2_CSHARP_COOKIE_CLEANED_COMMENT
    )
    assert (
        sanitize_comment("c#", STACK_V2_CSHARP_COOKIE_BLOCK_COMMENT)
        == STACK_V2_CSHARP_COOKIE_CLEANED_COMMENT
    )


def test_stack_v2_csharp_ornament_block_extracts_full_comment_with_offsets():
    matches = CommentQuery("c#").parse(STACK_V2_CSHARP_ORNAMENT_SOURCE)

    assert matches
    target = matches[0]
    start = len(target.prefix)
    end = start + len(target.match)
    line = target.prefix.count("\n") + 1
    last_line_break = target.prefix.rfind("\n")
    column = start + 1 if last_line_break == -1 else start - last_line_break

    assert target == QueryMatch(
        STACK_V2_CSHARP_ORNAMENT_SOURCE_PREFIX,
        STACK_V2_CSHARP_ORNAMENT_SOURCE_SUFFIX,
        STACK_V2_CSHARP_ORNAMENT_BLOCK_COMMENT,
    )
    assert (start, end, line, column) == (
        STACK_V2_CSHARP_ORNAMENT_MATCH_START,
        STACK_V2_CSHARP_ORNAMENT_MATCH_END,
        STACK_V2_CSHARP_ORNAMENT_MATCH_LINE,
        STACK_V2_CSHARP_ORNAMENT_MATCH_COLUMN,
    )


def test_stack_v2_csharp_ornament_block_sanitizes_author_credit():
    target = QueryMatch("", "", STACK_V2_CSHARP_ORNAMENT_BLOCK_COMMENT)

    assert (
        CommentSanitizer("c#").sanitize(target)
        == STACK_V2_CSHARP_ORNAMENT_CLEANED_COMMENT
    )
    assert (
        sanitize_comment("c#", STACK_V2_CSHARP_ORNAMENT_BLOCK_COMMENT)
        == STACK_V2_CSHARP_ORNAMENT_CLEANED_COMMENT
    )


def test_stack_v2_csharp_decorated_metadata_block_extracts_full_comment_with_offsets():
    prefix = _stack_v2_positioned_prefix(
        C_SHARP_STACK_V2_DECORATED_METADATA_MATCH_START,
        C_SHARP_STACK_V2_DECORATED_METADATA_MATCH_LINE,
        C_SHARP_STACK_V2_DECORATED_METADATA_MATCH_COLUMN,
        "",
    )
    source = (
        prefix
        + C_SHARP_STACK_V2_DECORATED_METADATA_BLOCK_COMMENT
        + C_SHARP_STACK_V2_DECORATED_METADATA_SOURCE_SUFFIX
    )

    matches = CommentQuery("c#").parse(source)

    assert matches
    target = matches[0]
    start = len(target.prefix)
    end = start + len(target.match)
    line = target.prefix.count("\n") + 1
    last_line_break = target.prefix.rfind("\n")
    column = start + 1 if last_line_break == -1 else start - last_line_break

    assert target == QueryMatch(
        prefix,
        C_SHARP_STACK_V2_DECORATED_METADATA_SOURCE_SUFFIX,
        C_SHARP_STACK_V2_DECORATED_METADATA_BLOCK_COMMENT,
    )
    assert (start, end, line, column) == (
        C_SHARP_STACK_V2_DECORATED_METADATA_MATCH_START,
        C_SHARP_STACK_V2_DECORATED_METADATA_MATCH_END,
        C_SHARP_STACK_V2_DECORATED_METADATA_MATCH_LINE,
        C_SHARP_STACK_V2_DECORATED_METADATA_MATCH_COLUMN,
    )


def test_stack_v2_csharp_decorated_metadata_block_sanitizes_gutters():
    target = QueryMatch("", "", C_SHARP_STACK_V2_DECORATED_METADATA_BLOCK_COMMENT)

    assert (
        CommentSanitizer("c#").sanitize(target)
        == C_SHARP_STACK_V2_DECORATED_METADATA_CLEANED_COMMENT
    )
    assert (
        sanitize_comment("c#", C_SHARP_STACK_V2_DECORATED_METADATA_BLOCK_COMMENT)
        == C_SHARP_STACK_V2_DECORATED_METADATA_CLEANED_COMMENT
    )


def test_stack_v2_csharp_bom_russian_header_extracts_full_comment_with_offsets():
    matches = CommentQuery("c#").parse(C_SHARP_STACK_V2_RECTANGLE_SOURCE)

    assert matches
    target = matches[0]
    start = len(target.prefix)
    end = start + len(target.match)
    line = target.prefix.count("\n") + 1
    last_line_break = target.prefix.rfind("\n")
    column = start + 1 if last_line_break == -1 else start - last_line_break

    assert target == QueryMatch(
        C_SHARP_STACK_V2_RECTANGLE_SOURCE_PREFIX,
        C_SHARP_STACK_V2_RECTANGLE_SOURCE_SUFFIX,
        C_SHARP_STACK_V2_RECTANGLE_BLOCK_COMMENT,
    )
    assert (start, end, line, column) == (
        C_SHARP_STACK_V2_RECTANGLE_MATCH_START,
        C_SHARP_STACK_V2_RECTANGLE_MATCH_END,
        C_SHARP_STACK_V2_RECTANGLE_MATCH_LINE,
        C_SHARP_STACK_V2_RECTANGLE_MATCH_COLUMN,
    )


def test_stack_v2_csharp_bom_russian_header_sanitizes_multiline_text():
    target = QueryMatch("", "", C_SHARP_STACK_V2_RECTANGLE_BLOCK_COMMENT)

    assert (
        CommentSanitizer("c#").sanitize(target)
        == C_SHARP_STACK_V2_RECTANGLE_CLEANED_COMMENT
    )
    assert (
        sanitize_comment("c#", C_SHARP_STACK_V2_RECTANGLE_BLOCK_COMMENT)
        == C_SHARP_STACK_V2_RECTANGLE_CLEANED_COMMENT
    )


def test_stack_v2_csharp_crlf_perlin_header_extracts_full_comment_with_offsets():
    matches = CommentQuery("c#").parse(C_SHARP_STACK_V2_PERLIN_SOURCE)

    assert matches
    target = matches[0]

    assert target == QueryMatch(
        C_SHARP_STACK_V2_PERLIN_SOURCE_PREFIX,
        C_SHARP_STACK_V2_PERLIN_SOURCE_SUFFIX,
        C_SHARP_STACK_V2_PERLIN_BLOCK_COMMENT,
    )
    assert _query_match_location(target) == (
        C_SHARP_STACK_V2_PERLIN_MATCH_START,
        C_SHARP_STACK_V2_PERLIN_MATCH_END,
        C_SHARP_STACK_V2_PERLIN_MATCH_LINE,
        C_SHARP_STACK_V2_PERLIN_MATCH_COLUMN,
    )


def test_stack_v2_csharp_crlf_perlin_header_sanitizes_reference_text():
    target = QueryMatch("", "", C_SHARP_STACK_V2_PERLIN_BLOCK_COMMENT)

    assert (
        CommentSanitizer("c#").sanitize(target)
        == C_SHARP_STACK_V2_PERLIN_CLEANED_COMMENT
    )
    assert (
        sanitize_comment("c#", C_SHARP_STACK_V2_PERLIN_BLOCK_COMMENT)
        == C_SHARP_STACK_V2_PERLIN_CLEANED_COMMENT
    )


def test_stack_v2_csharp_crlf_cgsoso_header_extracts_full_comment_with_offsets():
    matches = CommentQuery("c#").parse(C_SHARP_STACK_V2_CGSOSO_SOURCE)

    assert matches
    target = matches[0]

    assert target == QueryMatch(
        "",
        C_SHARP_STACK_V2_CGSOSO_SOURCE_SUFFIX,
        C_SHARP_STACK_V2_CGSOSO_BLOCK_COMMENT,
    )
    assert _query_match_location(target) == (
        C_SHARP_STACK_V2_CGSOSO_MATCH_START,
        C_SHARP_STACK_V2_CGSOSO_MATCH_END,
        C_SHARP_STACK_V2_CGSOSO_MATCH_LINE,
        C_SHARP_STACK_V2_CGSOSO_MATCH_COLUMN,
    )


def test_stack_v2_csharp_crlf_cgsoso_header_sanitizes_multilingual_text():
    target = QueryMatch("", "", C_SHARP_STACK_V2_CGSOSO_BLOCK_COMMENT)

    assert (
        CommentSanitizer("c#").sanitize(target)
        == C_SHARP_STACK_V2_CGSOSO_CLEANED_COMMENT
    )
    assert (
        sanitize_comment("c#", C_SHARP_STACK_V2_CGSOSO_BLOCK_COMMENT)
        == C_SHARP_STACK_V2_CGSOSO_CLEANED_COMMENT
    )


def test_stack_v2_csharp_adjacent_todo_lines_extract_as_single_comment_with_offsets():
    matches = CommentQuery("c#").parse(C_SHARP_STACK_V2_INTERACTION_TODO_SOURCE)

    assert matches
    target = matches[0]

    assert target == QueryMatch(
        C_SHARP_STACK_V2_INTERACTION_TODO_SOURCE_PREFIX,
        C_SHARP_STACK_V2_INTERACTION_TODO_SOURCE_SUFFIX,
        C_SHARP_STACK_V2_INTERACTION_TODO_LINE_COMMENT,
    )
    assert _query_match_location(target) == (
        C_SHARP_STACK_V2_INTERACTION_TODO_MATCH_START,
        C_SHARP_STACK_V2_INTERACTION_TODO_MATCH_END,
        C_SHARP_STACK_V2_INTERACTION_TODO_MATCH_LINE,
        C_SHARP_STACK_V2_INTERACTION_TODO_MATCH_COLUMN,
    )


def test_stack_v2_csharp_adjacent_todo_lines_sanitizer_strips_delimiters():
    target = QueryMatch("", "", C_SHARP_STACK_V2_INTERACTION_TODO_LINE_COMMENT)

    assert (
        CommentSanitizer("c#").sanitize(target)
        == C_SHARP_STACK_V2_INTERACTION_TODO_CLEANED_COMMENT
    )
    assert (
        sanitize_comment("c#", C_SHARP_STACK_V2_INTERACTION_TODO_LINE_COMMENT)
        == C_SHARP_STACK_V2_INTERACTION_TODO_CLEANED_COMMENT
    )


def test_stack_v2_csharp_startup_line_group_extracts_full_comment_with_offsets():
    matches = CommentQuery("c#").parse(C_SHARP_STACK_V2_STARTUP_SOURCE)

    assert matches == [
        QueryMatch(
            C_SHARP_STACK_V2_STARTUP_SOURCE_PREFIX,
            C_SHARP_STACK_V2_STARTUP_SOURCE_SUFFIX,
            C_SHARP_STACK_V2_STARTUP_LINE_COMMENT,
        )
    ]
    assert _query_match_location(matches[0]) == (
        C_SHARP_STACK_V2_STARTUP_MATCH_START,
        C_SHARP_STACK_V2_STARTUP_MATCH_END,
        C_SHARP_STACK_V2_STARTUP_MATCH_LINE,
        C_SHARP_STACK_V2_STARTUP_MATCH_COLUMN,
    )


def test_stack_v2_csharp_startup_line_group_sanitizes_delimiters_and_preserves_url():
    target = QueryMatch("", "", C_SHARP_STACK_V2_STARTUP_LINE_COMMENT)

    assert (
        CommentSanitizer("c#").sanitize(target)
        == C_SHARP_STACK_V2_STARTUP_CLEANED_COMMENT
    )
    assert (
        sanitize_comment("c#", C_SHARP_STACK_V2_STARTUP_LINE_COMMENT)
        == C_SHARP_STACK_V2_STARTUP_CLEANED_COMMENT
    )


def test_stack_v2_csharp_novartis_line_header_extracts_full_comment_with_offsets():
    matches = CommentQuery("c#").parse(C_SHARP_STACK_V2_NOVARTIS_SOURCE)

    assert matches == [
        QueryMatch(
            C_SHARP_STACK_V2_NOVARTIS_SOURCE_PREFIX,
            C_SHARP_STACK_V2_NOVARTIS_SOURCE_SUFFIX,
            C_SHARP_STACK_V2_NOVARTIS_LINE_COMMENT,
        )
    ]
    assert _query_match_location(matches[0]) == (
        C_SHARP_STACK_V2_NOVARTIS_MATCH_START,
        C_SHARP_STACK_V2_NOVARTIS_MATCH_END,
        C_SHARP_STACK_V2_NOVARTIS_MATCH_LINE,
        C_SHARP_STACK_V2_NOVARTIS_MATCH_COLUMN,
    )


def test_stack_v2_csharp_novartis_line_header_sanitizes_scaffolding_and_rulers():
    target = QueryMatch("", "", C_SHARP_STACK_V2_NOVARTIS_LINE_COMMENT)

    assert (
        CommentSanitizer("c#").sanitize(target)
        == C_SHARP_STACK_V2_NOVARTIS_CLEANED_COMMENT
    )
    assert (
        sanitize_comment("c#", C_SHARP_STACK_V2_NOVARTIS_LINE_COMMENT)
        == C_SHARP_STACK_V2_NOVARTIS_CLEANED_COMMENT
    )


def test_stack_v2_csharp_socket_xml_doc_extracts_full_comment_with_offsets():
    matches = CommentQuery("c#").parse(C_SHARP_STACK_V2_SOCKET_XML_DOC_SOURCE)

    assert matches == [
        QueryMatch(
            C_SHARP_STACK_V2_SOCKET_XML_DOC_SOURCE_PREFIX,
            C_SHARP_STACK_V2_SOCKET_XML_DOC_SOURCE_SUFFIX,
            C_SHARP_STACK_V2_SOCKET_XML_DOC_LINE_COMMENT,
        )
    ]
    assert _query_match_location(matches[0]) == (
        C_SHARP_STACK_V2_SOCKET_XML_DOC_MATCH_START,
        C_SHARP_STACK_V2_SOCKET_XML_DOC_MATCH_END,
        C_SHARP_STACK_V2_SOCKET_XML_DOC_MATCH_LINE,
        C_SHARP_STACK_V2_SOCKET_XML_DOC_MATCH_COLUMN,
    )


def test_stack_v2_csharp_socket_xml_doc_sanitizes_delimiters():
    target = QueryMatch("", "", C_SHARP_STACK_V2_SOCKET_XML_DOC_LINE_COMMENT)

    assert (
        CommentSanitizer("c#").sanitize(target)
        == C_SHARP_STACK_V2_SOCKET_XML_DOC_CLEANED_COMMENT
    )
    assert (
        sanitize_comment("c#", C_SHARP_STACK_V2_SOCKET_XML_DOC_LINE_COMMENT)
        == C_SHARP_STACK_V2_SOCKET_XML_DOC_CLEANED_COMMENT
    )


FORTH_STACK_V2_BARE_BACKSLASH_PREFIX = "-makelib ies/xil_defaultlib -sv "
FORTH_STACK_V2_BARE_BACKSLASH_COMMENT = "\\" + "\r"
FORTH_STACK_V2_BARE_BACKSLASH_SUFFIX = (
    "\n"
    '  "C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" '
    "\\"
    "\r\n"
    '  "C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_base.sv" '
    "\\"
    "\r\n"
)
FORTH_STACK_V2_BARE_BACKSLASH_SOURCE = (
    FORTH_STACK_V2_BARE_BACKSLASH_PREFIX
    + FORTH_STACK_V2_BARE_BACKSLASH_COMMENT
    + FORTH_STACK_V2_BARE_BACKSLASH_SUFFIX
)
FORTH_STACK_V2_HEADER_LINE_COMMENT = "\\ *** Block No. 131, Hexblock 83"

RAKU_STACK_V2_EMBEDDED_BLOCK_COMMENT = (
    "#`(\n"
    "#| A cool\n"
    "constant $pi = 3.14159;\n"
    "#= constant\n"
    "\n"
    "test-both($pi.VAR, 'A cool', 'constant');\n"
    ")"
)
RAKU_STACK_V2_EMBEDDED_BLOCK_SOURCE = (
    "skip 'declaration comments are NYI on constants', 7;\n"
    + RAKU_STACK_V2_EMBEDDED_BLOCK_COMMENT
    + "\n\nskip 'declaration comments are NYI on variables', 7;\n"
)
RAKU_STACK_V2_EMBEDDED_BLOCK_CLEANED = (
    "#| A cool\n"
    "constant $pi = 3.14159;\n"
    "#= constant\n"
    "\n"
    "test-both($pi.VAR, 'A cool', 'constant');"
)
RAKU_RAKUDOC_COMMENT_BLOCK = "=begin comment\nThis is hidden.\n=end comment"
RAKU_RAKUDOC_SOURCE = "unit module Example;\n" + RAKU_RAKUDOC_COMMENT_BLOCK + "\nsub x {}\n"


def test_stack_v2_forth_bare_backslash_extracts_only_line_comment():
    matches = CommentQuery("forth").parse(FORTH_STACK_V2_BARE_BACKSLASH_SOURCE)

    assert matches
    assert matches[0] == QueryMatch(
        FORTH_STACK_V2_BARE_BACKSLASH_PREFIX,
        FORTH_STACK_V2_BARE_BACKSLASH_SUFFIX,
        FORTH_STACK_V2_BARE_BACKSLASH_COMMENT,
    )
    assert "xpm_cdc" not in matches[0].match


def test_stack_v2_forth_bare_backslash_sanitizes_to_empty_comment():
    target = QueryMatch("", "", FORTH_STACK_V2_BARE_BACKSLASH_COMMENT)

    assert CommentSanitizer("forth").sanitize(target) == ""
    assert sanitize_comment("forth", FORTH_STACK_V2_BARE_BACKSLASH_COMMENT) == ""


def test_stack_v2_forth_regular_backslash_comment_still_sanitizes_content():
    target = QueryMatch("", "", FORTH_STACK_V2_HEADER_LINE_COMMENT)

    assert CommentSanitizer("forth").sanitize(target) == "*** Block No. 131, Hexblock 83"
    assert (
        sanitize_comment("forth", FORTH_STACK_V2_HEADER_LINE_COMMENT)
        == "*** Block No. 131, Hexblock 83"
    )


def test_stack_v2_raku_embedded_comment_handles_inner_parentheses():
    matches = CommentQuery("raku").parse(RAKU_STACK_V2_EMBEDDED_BLOCK_SOURCE)

    assert matches == [
        QueryMatch(
            "skip 'declaration comments are NYI on constants', 7;\n",
            "\n\nskip 'declaration comments are NYI on variables', 7;\n",
            RAKU_STACK_V2_EMBEDDED_BLOCK_COMMENT,
        )
    ]


def test_stack_v2_raku_embedded_comment_sanitizes_full_body():
    target = QueryMatch("", "", RAKU_STACK_V2_EMBEDDED_BLOCK_COMMENT)

    assert CommentSanitizer("raku").sanitize(target) == RAKU_STACK_V2_EMBEDDED_BLOCK_CLEANED
    assert (
        sanitize_comment("raku", RAKU_STACK_V2_EMBEDDED_BLOCK_COMMENT)
        == RAKU_STACK_V2_EMBEDDED_BLOCK_CLEANED
    )


def test_stack_v2_raku_rakudoc_comment_block_extracts_and_sanitizes():
    matches = CommentQuery("raku").parse(RAKU_RAKUDOC_SOURCE)

    assert matches == [
        QueryMatch(
            "unit module Example;\n",
            "\nsub x {}\n",
            RAKU_RAKUDOC_COMMENT_BLOCK,
        )
    ]
    assert CommentSanitizer("raku").sanitize(matches[0]) == "This is hidden."


def test_stack_v2_raku_mixed_declarator_lines_strip_each_prefix():
    raw_comment = "#| leading declarator\n#= trailing declarator"

    assert (
        CommentSanitizer("raku").sanitize(QueryMatch("", "", raw_comment))
        == "leading declarator\ntrailing declarator"
    )
    assert (
        sanitize_comment("raku", raw_comment)
        == "leading declarator\ntrailing declarator"
    )


AUTOHOTKEY_STACK_V2_CR_ONLY_SOURCE = (
    '; Stay Current Window Always on Top\r'
    'CapsLock & `:: Do({func: "TopCurrentWindow"}, '
    '{func: "ShowOrHideFiles", csa: "001"})\r'
    "\r"
    "; Rotate Display Screen 1/2/3\r"
    'CapsLock & Up:: Do({func: "RotateDisplay", param: {deg: 0}}\r'
)
AUTOHOTKEY_STACK_V2_FIRST_LINE_COMMENT = "; Stay Current Window Always on Top\r"
AUTOHOTKEY_STACK_V2_SECOND_LINE_COMMENT = "; Rotate Display Screen 1/2/3\r"

PROLOG_STACK_V2_SEPARATOR = (
    "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
    "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
    "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
)
PROLOG_STACK_V2_SOURCE = (
    "/*\n"
    "Find out whether a list is a palindrome.\n"
    "A palindrome can be read forward or backward; e.g. [x,a,m,a,x].\n"
    "*/\n"
    f"{PROLOG_STACK_V2_SEPARATOR}\n"
    "\n"
    "check_palindrome([H|T]):-\n"
    "    reverse1([H|T],Reverse,[]),\n"
    "    [H|T]=Reverse.\n"
    "\n"
    f"{PROLOG_STACK_V2_SEPARATOR}\n"
    "/* Execute the Program:-\n"
    "?-check_palindrome([l,o,l]).\n"
    "*/\n"
)

STACK_V2_REPORTED_EXTRACTION_CASES = (
    pytest.param(
        "d",
        "*/\n"
        "int runApplication(string[]* args_out = null) { return 0; }\n"
        "/// A simple echo server, listening on a privileged TCP port.\n"
        "unittest {\n"
        "    // first, perform any application specific setup\n"
        "}\n",
        "/// A simple echo server, listening on a privileged TCP port.",
        id="d-line-695baf7d4001e436",
    ),
    pytest.param(
        "erlang",
        "%%%-------------------------------------------------------------------\n"
        "%% @doc nfdemo public API\n"
        "%% @end\n"
        "%%%-------------------------------------------------------------------\n"
        "\n"
        "-module(nfdemo_app).\n",
        "%%%-------------------------------------------------------------------\n"
        "%% @doc nfdemo public API\n"
        "%% @end\n"
        "%%%-------------------------------------------------------------------",
        id="erlang-line-d377a7a07c46ba63",
    ),
    pytest.param(
        "fortran",
        "!------------------------------------------------------------------------------\n"
        "!                  GEOS-Chem Global Chemical Transport Model                  !\n"
        "!------------------------------------------------------------------------------\n"
        "!BOP\n"
        "!\n"
        "! !MODULE: vistas_anthro_mod\n"
        "!\n"
        "! !DESCRIPTION: Module VISTAS\\_ANTHRO\\_MOD contains variables and routines \n"
        "!  to read the VISTAS anthropogenic emissions.\n"
        "!\\\\\n"
        "!\\\\\n"
        "! !INTERFACE: \n"
        "!\n"
        "      MODULE VISTAS_ANTHRO_MOD\n",
        "!------------------------------------------------------------------------------\n"
        "!                  GEOS-Chem Global Chemical Transport Model                  !\n"
        "!------------------------------------------------------------------------------\n"
        "!BOP\n"
        "!\n"
        "! !MODULE: vistas_anthro_mod\n"
        "!\n"
        "! !DESCRIPTION: Module VISTAS\\_ANTHRO\\_MOD contains variables and routines \n"
        "!  to read the VISTAS anthropogenic emissions.\n"
        "!\\\\\n"
        "!\\\\\n"
        "! !INTERFACE: \n"
        "!",
        id="fortran-line-5d4096b01df90d1e",
    ),
    pytest.param(
        "lua",
        "function M:_get_packed_object(path, name)\r\n"
        "\treturn cobj, tw, th\r\n"
        "end\r\n"
        "\r\n"
        "----------------------------image-------------------------------\r\n"
        "function M:load_image(path, name, pic_callback)\r\n"
        "\treturn spr, tw, th\r\n"
        "end\r\n",
        "----------------------------image-------------------------------\r",
        id="lua-line-a2ff8eca29a389c8",
    ),
    pytest.param(
        "mathematica",
        'exeLinkLibraries[_] := "-lm -lpthread -lrt -ldl"\r\n'
        "\r\n"
        "(*****************************************************************************)\r\n"
        "(* Automatic installation detection *)\r\n"
        "\r\n"
        '$PathDirs = StringSplit[Environment["PATH"], $PlatformPathSeparator]\r\n',
        "(*****************************************************************************)",
        id="mathematica-nested-3248c6016956a958",
    ),
)


def test_stack_v2_autohotkey_cr_only_line_comments_stop_at_carriage_return():
    matches = CommentQuery("autohotkey").parse(AUTOHOTKEY_STACK_V2_CR_ONLY_SOURCE)

    assert [match.match for match in matches] == [
        AUTOHOTKEY_STACK_V2_FIRST_LINE_COMMENT,
        AUTOHOTKEY_STACK_V2_SECOND_LINE_COMMENT,
    ]
    assert "CapsLock & `::" not in matches[0].match
    assert "CapsLock & Up::" not in matches[1].match


def test_stack_v2_xojo_cr_only_apostrophe_line_comment_stops_at_carriage_return():
    source = (
        "Sub Constructor(f as FolderItem)\r"
        "  ' saves the current res file\r"
        "  dim ref as MemoryBlock = f.MacFSRef\r"
        "  if ref = nil then\r"
        "    break ' file not accessible\r"
        "  end if\r"
        "End Sub\r"
    )

    raw_comments = [match.match for match in CommentQuery("xojo").parse(source)]

    assert raw_comments == [
        "' saves the current res file",
        "' file not accessible",
    ]
    assert all("dim ref" not in comment for comment in raw_comments)


def test_stack_v2_brainfuck_ignored_text_is_scanned_at_run_boundaries():
    source = "+++++[>++++<-] Brainfuck note\n+" + ("A" * 500) + "\n."

    raw_comments = [match.match for match in CommentQuery("brainfuck").parse(source)]
    raw_ranges = list(LineCommentQuery("brainfuck")._iter_match_ranges(source))

    assert raw_comments == ["Brainfuck note", "A" * 500]
    assert raw_ranges == [(15, 29), (31, 531)]


@pytest.mark.parametrize(
    ("language", "source", "expected_raw_comment"),
    STACK_V2_REPORTED_EXTRACTION_CASES,
)
def test_stack_v2_reported_extraction_includes_expected_raw_comment(
    language, source, expected_raw_comment
):
    raw_comments = [match.match for match in CommentQuery(language).parse(source)]

    assert expected_raw_comment in raw_comments


def test_stack_v2_prolog_percent_line_does_not_group_with_following_block():
    matches = CommentQuery("prolog").parse(PROLOG_STACK_V2_SOURCE)
    raw_comments = [match.match for match in matches]

    assert PROLOG_STACK_V2_SEPARATOR in raw_comments
    assert f"{PROLOG_STACK_V2_SEPARATOR}\n/* Execute" not in raw_comments
