#!/usr/bin/env python3
"""
Batch visualize EBNF grammars (railroad diagrams) for multiple languages.

- Input grammars: src/ml4setk/EBNF/ebnfs/*.ebnf
- Per-language rule svgs are generated by ebnf.py into src/ml4setk/EBNF/results/<language>
- This script copies those svgs into <repo_root>/visualization/<language>/rules
- Then it generates a combined.svg for each language via combine_svg.py
- If --counts-json is provided, it colors per-position based on rule counts and builds colored_combined.svg

Usage:
  python visualize_grammars.py                               # visualize all languages in ebnfs/
  python visualize_grammars.py --languages python,java,go
  python visualize_grammars.py --languages python --counts-json path/to/counts.json
"""

import argparse
import shutil
import subprocess
import sys
from pathlib import Path
from typing import List, Optional
import importlib

THIS_FILE = Path(__file__).resolve()
EBNF_DIR = THIS_FILE.parent
PROJECT_SRC_DIR = EBNF_DIR.parent.parent   # src/
REPO_ROOT = PROJECT_SRC_DIR.parent         # repo root
EBNFS_DIR = EBNF_DIR / "ebnfs"
RESULTS_DIR = EBNF_DIR / "results"
VIS_ROOT = REPO_ROOT / "visualization"

def run(cmd: List[str], cwd: Path) -> int:
    print(f"[RUN] {' '.join(cmd)}  (cwd={cwd})")
    proc = subprocess.Popen(cmd, cwd=str(cwd))
    return proc.wait()

def list_languages_from_ebnfs() -> List[str]:
    langs = []
    for p in sorted(EBNFS_DIR.glob("*.ebnf")):
        langs.append(p.stem)
    return langs

def ensure_dir(p: Path):
    p.mkdir(parents=True, exist_ok=True)

def visualize_language(lang: str, counts_json: Optional[str] = None) -> bool:
    """
    Generate per-rule svgs via ebnf.py, copy to visualization, and create combined.svg.
    If counts_json is provided, color per-position and create colored_combined.svg.
    """
    ebnf_file = EBNFS_DIR / f"{lang}.ebnf"
    if not ebnf_file.exists():
        print(f"[WARN] EBNF file not found for language '{lang}': {ebnf_file}")
        return False

    # 1) Generate per-rule svgs using ebnf.py (outputs to EBNF/results/<lang>)
    print(f"\n=== Visualizing language: {lang} ===")
    ret = run([sys.executable, "ebnf.py", str(ebnf_file)], cwd=EBNF_DIR)
    if ret != 0:
        print(f"[ERROR] ebnf.py failed for {lang} (exit={ret})")
        return False

    per_rule_src_dir = RESULTS_DIR / lang
    if not per_rule_src_dir.exists():
        print(f"[ERROR] Expected results dir missing: {per_rule_src_dir}")
        return False

    # 2) Prepare visualization target dirs
    vis_lang_dir = VIS_ROOT / lang
    vis_rules_dir = vis_lang_dir / "rules"
    ensure_dir(vis_rules_dir)

    # 3) Copy all generated svgs to visualization/<lang>/rules
    copied = 0
    for svg in sorted(per_rule_src_dir.glob("*.svg")):
        shutil.copy2(svg, vis_rules_dir / svg.name)
        copied += 1
    print(f"[INFO] Copied {copied} rule svgs to {vis_rules_dir}")

    # 4) Generate combined.svg into visualization/<lang>/combined.svg
    combined_out = vis_lang_dir / "combined.svg"
    ret = run([sys.executable, "combine_svg.py", str(vis_rules_dir), str(combined_out)], cwd=EBNF_DIR)
    if ret != 0:
        print(f"[ERROR] combine_svg.py failed for {lang} (exit={ret})")
        return False

    # 5) Optional coloring based on counts json
    if counts_json:
        try:
            from color_visualization import color_svgs
        except Exception:
            color_svgs = importlib.import_module("color_visualization").color_svgs

        vis_colored_dir = vis_lang_dir / "colored"
        colored, total, gmax = color_svgs(str(vis_rules_dir), counts_json, str(vis_colored_dir))
        print(f"[INFO] Colored {colored}/{total} svgs (global_max={gmax}) at {vis_colored_dir}")

        # Build colored combined svg
        colored_combined_out = vis_lang_dir / "colored_combined.svg"
        ret = run([sys.executable, "combine_svg.py", str(vis_colored_dir), str(colored_combined_out)], cwd=EBNF_DIR)
        if ret != 0:
            print(f"[ERROR] combine_svg.py (colored) failed for {lang} (exit={ret})")
            return False

        print(f"[DONE] Language {lang}: combined.svg at {combined_out}, colored_combined.svg at {colored_combined_out}")
    else:
        print(f"[DONE] Language {lang}: combined.svg at {combined_out}")

    return True

def main():
    parser = argparse.ArgumentParser(description="Batch visualize EBNF grammars to railroad diagrams")
    parser.add_argument("--languages", help="Comma-separated list of languages to visualize (default: all)")
    parser.add_argument("--counts-json", help="Rule counts JSON from rule_counter.py to color diagrams", default=None)
    args = parser.parse_args()

    ensure_dir(VIS_ROOT)

    if args.languages:
        targets = [x.strip() for x in args.languages.split(",") if x.strip()]
    else:
        targets = list_languages_from_ebnfs()

    if not targets:
        print("[INFO] No languages found to visualize.")
        return

    print(f"[INFO] Visualization root: {VIS_ROOT}")
    print(f"[INFO] Targets: {', '.join(targets)}")

    ok = 0
    for lang in targets:
        if visualize_language(lang, counts_json=args.counts_json):
            ok += 1

    print(f"\nSummary: {ok}/{len(targets)} languages visualized.")
    print(f"Output root: {VIS_ROOT}")

if __name__ == "__main__":
    main()