#!/usr/bin/env python3
"""Build adversarial comment-testing prompt packets for supported languages."""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import dataclass
from pathlib import Path

from ml4setk import get_supported_comment_languages
from ml4setk.Parsing.Comments import get_comment_syntax

ROOT = Path(__file__).resolve().parents[1]
TESTING_DIR = ROOT / "docs" / "comment_testing"
PROMPT_DIR = TESTING_DIR / "prompt_packets"
THREAD_DIR = TESTING_DIR / "threads"
ASSIGNMENTS_PATH = TESTING_DIR / "agent_chunk_assignments.json"
DEFAULT_CHUNK_COUNT = 8


@dataclass(frozen=True)
class LanguageContext:
    """One supported language with the registry family that implements it."""

    language: str
    family_name: str
    notes: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build adversarial comment-testing prompt packets."
    )
    parser.add_argument(
        "--chunk-count",
        type=int,
        default=DEFAULT_CHUNK_COUNT,
        help="Number of language chunks to generate.",
    )
    return parser.parse_args()


def build_language_contexts() -> list[LanguageContext]:
    contexts = []
    for language in get_supported_comment_languages():
        syntax = get_comment_syntax(language)
        contexts.append(
            LanguageContext(
                language=language,
                family_name=syntax.family_name,
                notes=syntax.notes,
            )
        )
    return contexts


def chunk_contexts(
    contexts: list[LanguageContext], chunk_count: int
) -> list[tuple[str, list[LanguageContext]]]:
    if chunk_count < 1:
        raise ValueError("chunk_count must be at least 1")
    if not contexts:
        return []

    chunk_size = math.ceil(len(contexts) / chunk_count)
    chunks = []
    for index, start in enumerate(range(0, len(contexts), chunk_size)):
        chunks.append((f"chunk_{index}", contexts[start : start + chunk_size]))
    return chunks


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def maybe_write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        path.write_text(content, encoding="utf-8")


def render_language_scope(contexts: list[LanguageContext]) -> str:
    lines = ["| Language | Family | Notes |", "| --- | --- | --- |"]
    for context in contexts:
        notes = context.notes.replace("|", "\\|") if context.notes else ""
        if not notes:
            notes = "-"
        lines.append(
            f"| `{context.language}` | `{context.family_name}` | {notes} |"
        )
    return "\n".join(lines)


def render_breaker_prompt(chunk_name: str, contexts: list[LanguageContext]) -> str:
    findings_path = f"docs/comment_testing/threads/{chunk_name}_findings.md"
    resolution_path = f"docs/comment_testing/threads/{chunk_name}_resolution.md"
    return "\n".join(
        [
            f"# Breaker Packet: {chunk_name}",
            "",
            "Generated by `scripts/build_comment_test_packets.py`. Do not edit this",
            "file by hand.",
            "",
            "## Goal",
            "",
            "Produce adversarial parser inputs for the assigned languages. Focus on",
            "cases that are likely to expose missing tests, ambiguous contracts, or",
            "comment-syntax edge cases that the current suite does not yet lock down.",
            "",
            "## Ownership",
            "",
            f"- Write findings only to `{findings_path}`.",
            f"- Read `{resolution_path}` for already-handled cases, but do not edit it.",
            "- Do not edit production code, registry entries, or test files.",
            "",
            "## Required workflow",
            "",
            "1. Inspect the registry, generated tests, and targeted tests for each",
            "   assigned language.",
            "2. Try to break the current assumptions with minimal inputs.",
            "3. If a scenario is believed not to exist for the language, search",
            "   the internet for real examples anyway and use them as crash or",
            "   misparse probes.",
            "4. Run the parser locally and record the actual result for each case.",
            "5. Only keep cases that are either currently failing, currently",
            "   ambiguous, or missing explicit regression coverage.",
            "6. Prefer 1-3 high-value cases per language over broad low-signal spam.",
            "",
            "## Adversarial themes",
            "",
            "- Outer block comments containing inner line-comment markers.",
            "- Nested openers and closers at different depths.",
            "- Unterminated blocks and stray closing delimiters.",
            "- Adjacent standalone line comments vs inline comments.",
            "- Indentation-sensitive or column-sensitive comment forms.",
            "- Version or dialect variants that share one registry key.",
            "- Quote-delimited comments containing delimiter-like text.",
            "- Opening file-header comments and hashbang interaction.",
            "- Unsupported or disputed comment forms found in real examples online.",
            "",
            "## Unsupported-scenario probing",
            "",
            "When prior research or registry notes imply that a comment form does",
            "not exist, do not stop there. Search the web for real examples and",
            "probe the parser with them anyway.",
            "",
            "Do not limit that search to Stack Overflow. GitHub, SourceForge,",
            "official docs, issue trackers, blogs, tutorials, mailing lists, and",
            "code-search results are all valid sources when they provide concrete",
            "comment examples.",
            "",
            "Suggested searches:",
            '- `"<Language> programming language comment"`',
            '- `"<Language> programming language block comment"`',
            '- `"<Language> programming language nested comment"`',
            '- `"site:stackoverflow.com <Language> programming language comment"`',
            '- `"site:github.com <Language> programming language comment"`',
            '- `"site:sourceforge.net <Language> programming language comment"`',
            '- `"<Language> programming language <delimiter> comment"`',
            "",
            "Keep only cases that reveal crashes, exceptions, hangs, obviously",
            "wrong matches, or missing explicit regression coverage.",
            "",
            "## Output format",
            "",
            "For each kept case, record:",
            "- the exact input",
            "- the parser entry point used",
            "- the actual output",
            "- the expected behavior",
            "- the source URL or provenance when the case came from the internet",
            "- why the case matters",
            "",
            "## Assigned languages",
            "",
            render_language_scope(contexts),
        ]
    )


def render_fixer_prompt(chunk_name: str, contexts: list[LanguageContext]) -> str:
    findings_path = f"docs/comment_testing/threads/{chunk_name}_findings.md"
    resolution_path = f"docs/comment_testing/threads/{chunk_name}_resolution.md"
    return "\n".join(
        [
            f"# Fixer Packet: {chunk_name}",
            "",
            "Generated by `scripts/build_comment_test_packets.py`. Do not edit this",
            "file by hand.",
            "",
            "## Goal",
            "",
            "Consume confirmed breaker findings and convert them into stable coverage.",
            "For valid failures, add regression tests first, then patch the parser or",
            "registry with the smallest coherent change.",
            "",
            "## Ownership",
            "",
            f"- Read `{findings_path}`.",
            f"- Write resolution notes to `{resolution_path}`.",
            "- You may edit parser code, registry entries, tests, and user-facing",
            "  comment-parser docs as needed.",
            "- Do not rewrite breaker findings or other chunks.",
            "",
            "## Required workflow",
            "",
            "1. Validate each breaker case locally before changing code.",
            "2. Add or extend tests for every confirmed bug or missing contract.",
            "3. Patch the parser or registry minimally.",
            "4. If a case reflects an intentional limitation, document that instead of",
            "   forcing speculative support.",
            "5. Run targeted tests first, then the default non-optional suite if the",
            "   change touches shared parser behavior.",
            "",
            "## Resolution categories",
            "",
            "- `fixed-in-code`: parser or registry behavior changed.",
            "- `fixed-in-tests`: behavior was already correct, but coverage was missing.",
            "- `documented-limitation`: no code change; the case is now explicit.",
            "- `needs-policy-decision`: blocked on intended semantics.",
            "",
            "## Assigned languages",
            "",
            render_language_scope(contexts),
        ]
    )


def render_findings_skeleton(chunk_name: str, contexts: list[LanguageContext]) -> str:
    lines = [
        f"# Adversarial Findings: {chunk_name}",
        "",
        "Generated by `scripts/build_comment_test_packets.py`. This file is",
        "breaker-owned.",
        "",
        "## Scope",
        "",
        f"- Language count: `{len(contexts)}`",
        "- Status: `pending` until findings are recorded",
        "",
        "## Languages",
        "",
    ]
    for context in contexts:
        lines.extend(
            [
                f"### {context.language}",
                "",
                f"- Family: `{context.family_name}`",
                "- Status: pending",
                "- Findings:",
                "  - TODO",
                "",
            ]
        )
    return "\n".join(lines)


def render_resolution_skeleton(chunk_name: str, contexts: list[LanguageContext]) -> str:
    lines = [
        f"# Adversarial Resolution: {chunk_name}",
        "",
        "Generated by `scripts/build_comment_test_packets.py`. This file is",
        "fixer-owned.",
        "",
        "## Resolution log",
        "",
    ]
    for context in contexts:
        lines.extend(
            [
                f"### {context.language}",
                "",
                "- Status: pending",
                "- Resolution: TODO",
                "- Tests: TODO",
                "",
            ]
        )
    return "\n".join(lines)


def render_prompt_index(chunks: list[tuple[str, list[LanguageContext]]]) -> str:
    lines = [
        "# Comment Testing Prompt Packets",
        "",
        "Generated by `scripts/build_comment_test_packets.py`. Do not edit this",
        "file by hand.",
        "",
        "## Summary",
        "",
        f"- Chunk count: `{len(chunks)}`",
        f"- Supported language count: `{sum(len(contexts) for _, contexts in chunks)}`",
        "",
        "## Packets",
        "",
        "| Chunk | Languages | Breaker prompt | Fixer prompt | Findings | Resolution |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for chunk_name, contexts in chunks:
        lines.append(
            "| {chunk} | {count} | `{chunk}_breaker_prompt.md` | "
            "`{chunk}_fixer_prompt.md` | `{chunk}_findings.md` | "
            "`{chunk}_resolution.md` |".format(
                chunk=chunk_name,
                count=len(contexts),
            )
        )
    return "\n".join(lines)


def build_assignments(chunks: list[tuple[str, list[LanguageContext]]]) -> dict[str, object]:
    return {
        "supported_language_count": sum(len(contexts) for _, contexts in chunks),
        "chunk_count": len(chunks),
        "chunks": {
            chunk_name: [context.language for context in contexts]
            for chunk_name, contexts in chunks
        },
    }


def main() -> int:
    args = parse_args()
    contexts = build_language_contexts()
    chunks = chunk_contexts(contexts, args.chunk_count)

    write_text(
        ASSIGNMENTS_PATH,
        json.dumps(build_assignments(chunks), indent=2, sort_keys=True) + "\n",
    )

    for chunk_name, chunk_contexts_ in chunks:
        write_text(
            PROMPT_DIR / f"{chunk_name}_breaker_prompt.md",
            render_breaker_prompt(chunk_name, chunk_contexts_),
        )
        write_text(
            PROMPT_DIR / f"{chunk_name}_fixer_prompt.md",
            render_fixer_prompt(chunk_name, chunk_contexts_),
        )
        maybe_write_text(
            THREAD_DIR / f"{chunk_name}_findings.md",
            render_findings_skeleton(chunk_name, chunk_contexts_),
        )
        maybe_write_text(
            THREAD_DIR / f"{chunk_name}_resolution.md",
            render_resolution_skeleton(chunk_name, chunk_contexts_),
        )

    write_text(PROMPT_DIR / "README.md", render_prompt_index(chunks))

    print(f"Wrote {ASSIGNMENTS_PATH.relative_to(ROOT)}")
    print(f"Wrote {PROMPT_DIR.relative_to(ROOT) / 'README.md'}")
    print(f"Supported languages: {len(contexts)}")
    print(f"Chunks: {len(chunks)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
