#!/usr/bin/env python3
"""Build adversarial comment-testing prompt packets for supported languages."""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import dataclass
from pathlib import Path

from build_comment_language_fixtures import FIXTURE_DIR, language_fixture_filename

from ml4setk import get_supported_comment_languages
from ml4setk.Parsing.Comments import get_comment_syntax

ROOT = Path(__file__).resolve().parents[1]
TESTING_DIR = ROOT / "docs" / "comment_testing"
PROMPT_DIR = TESTING_DIR / "prompt_packets"
THREAD_DIR = TESTING_DIR / "threads"
ASSIGNMENTS_PATH = TESTING_DIR / "agent_chunk_assignments.json"
DEFAULT_CHUNK_COUNT = 8


@dataclass(frozen=True)
class LanguageContext:
    """One supported language with the registry family that implements it."""

    language: str
    family_name: str
    fixture_path: str
    notes: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build adversarial comment-testing prompt packets."
    )
    parser.add_argument(
        "--chunk-count",
        type=int,
        default=DEFAULT_CHUNK_COUNT,
        help="Number of language chunks to generate.",
    )
    return parser.parse_args()


def build_language_contexts() -> list[LanguageContext]:
    contexts = []
    for language in get_supported_comment_languages():
        syntax = get_comment_syntax(language)
        contexts.append(
            LanguageContext(
                language=language,
                family_name=syntax.family_name,
                fixture_path=(FIXTURE_DIR / language_fixture_filename(language)).as_posix(),
                notes=syntax.notes,
            )
        )
    return contexts


def chunk_contexts(
    contexts: list[LanguageContext], chunk_count: int
) -> list[tuple[str, list[LanguageContext]]]:
    if chunk_count < 1:
        raise ValueError("chunk_count must be at least 1")
    if not contexts:
        return []

    chunk_size = math.ceil(len(contexts) / chunk_count)
    chunks = []
    for index, start in enumerate(range(0, len(contexts), chunk_size)):
        chunks.append((f"chunk_{index}", contexts[start : start + chunk_size]))
    return chunks


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def maybe_write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        path.write_text(content, encoding="utf-8")


def render_language_scope(contexts: list[LanguageContext]) -> str:
    lines = ["| Language | Family | Fixture | Notes |", "| --- | --- | --- | --- |"]
    for context in contexts:
        notes = context.notes.replace("|", "\\|") if context.notes else ""
        if not notes:
            notes = "-"
        lines.append(
            f"| `{context.language}` | `{context.family_name}` | "
            f"`{context.fixture_path}` | {notes} |"
        )
    return "\n".join(lines)


def render_breaker_prompt(chunk_name: str, contexts: list[LanguageContext]) -> str:
    findings_path = f"docs/comment_testing/threads/{chunk_name}_findings.md"
    resolution_path = f"docs/comment_testing/threads/{chunk_name}_resolution.md"
    return "\n".join(
        [
            f"# Breaker Packet: {chunk_name}",
            "",
            "Generated by `scripts/build_comment_test_packets.py`. Do not edit this",
            "file by hand.",
            "",
            "## Goal",
            "",
            "Produce systematic parser and sanitizer coverage for the assigned",
            "languages. Cover all relevant scenario families, not only the most",
            "interesting failures, and leave an explicit outcome for each reviewed",
            "language.",
            "",
            "## Ownership",
            "",
            f"- Write findings to `{findings_path}`.",
            f"- Read `{resolution_path}` for already-handled cases, but do not edit it.",
            f"- Add parseable adversarial cases directly to assigned fixture files under "
            f"`{FIXTURE_DIR.as_posix()}/`.",
            "- Each language's fixture path is listed in the assignment table below.",
            "- Do not edit production code, registry entries, regular test modules,",
            "  fixer resolution files, or non-assigned fixture files.",
            "",
            "## Required workflow",
            "",
            "1. Inspect the registry, generated tests, targeted tests, and assigned",
            "   fixture file for each language.",
            "2. Enumerate the relevant scenario families for each language.",
            "3. Add minimal representative cases to the assigned fixture file when",
            "   the case should parse correctly with current behavior.",
            "4. Preserve the seeded fixture cases and separate added comments with",
            "   non-comment code lines when needed to avoid accidental line-comment",
            "   grouping.",
            "5. If a scenario is believed not to exist for the language, search",
            "   the internet for real examples anyway and use them as crash or",
            "   misparse probes.",
            "6. Run the parser locally and record the actual result for each case.",
            "   Cases left in fixture files must still parse correctly.",
            "7. If a candidate exposes a parser failure, do not leave it as a",
            "   fixture edit; record it in findings for a fixer-owned regression.",
            "8. When sanitizer behavior is in scope, record both the raw extracted",
            "   match and the sanitized output.",
            "9. For sanitizer cases, state which characters should be removed as",
            "   syntax noise and which must remain because they carry meaning.",
            "10. If a sanitizer case removes a symbol, add a paired case where the",
            "   same symbol is preserved because it is meaningful content.",
            "11. Run `uv run pytest tests/test_comment_language_fixtures.py -q --no-cov`",
            "   after fixture edits.",
            "12. Record an explicit outcome for every reviewed scenario family:",
            "   confirmed bug, ambiguous contract, or reviewed-no-issue.",
            "13. Use representative cases rather than redundant duplicates, but do",
            "   not skip coverage because a case is lower-priority.",
            "",
            "## Coverage themes",
            "",
            "Systematically review these as applicable to each assigned language:",
            "- Outer block comments containing inner line-comment markers.",
            "- Nested openers and closers at different depths.",
            "- Unterminated blocks and stray closing delimiters.",
            "- Adjacent standalone line comments vs inline comments.",
            "- Indentation-sensitive or column-sensitive comment forms.",
            "- Version or dialect variants that share one registry key.",
            "- Quote-delimited comments containing delimiter-like text.",
            "- Opening file-header comments and hashbang interaction.",
            "- Sanitizer under-stripping of delimiters, decorative gutters, or",
            "  delimiter-only edge lines.",
            "- Sanitizer over-stripping of Markdown markers, bullets, TODO tags,",
            "  code examples, CLI flags, or deliberate repeated punctuation.",
            "- Unsupported or disputed comment forms found in real examples online.",
            "",
            "## Sanitizer-specific expectations",
            "",
            "A good sanitizer removes comment scaffolding without erasing meaningful",
            "text.",
            "",
            "Treat these as removable only when they are acting as syntax noise:",
            "- outer delimiters and delimiter-only edge lines",
            "- decorative per-line gutters such as repeated leading `*`, `#`, `--`,",
            "  `;`, `%`, or `'` characters used only for formatting",
            "- padding-only indentation introduced by aligned block comments",
            "",
            "Treat these as preservation-sensitive when they are part of the",
            "comment body:",
            "- Markdown headings, bullets, emphasis, and checklists",
            "- tags such as `TODO:`, `FIXME:`, `@param`, or `@return`",
            "- shell and CLI text such as `#!/bin/sh`, `--flag`, `$HOME`, or `%VAR%`",
            "- code and language tokens such as `C#`, `F#`, `C++`, `#include`, `::`,",
            "  `**kwargs`, `%%time`, or `%matplotlib`",
            "",
            "Paired-case rule:",
            "- if one testcase proves that a symbol should be removed, add a",
            "  companion testcase proving that the same symbol must be kept when it",
            "  carries meaning",
            "",
            "## Unsupported-scenario probing",
            "",
            "When prior research or registry notes imply that a comment form does",
            "not exist, do not stop there. Search the web for real examples and",
            "probe the parser with them anyway.",
            "",
            "Do not limit that search to Stack Overflow. GitHub, SourceForge,",
            "official docs, issue trackers, blogs, tutorials, mailing lists, and",
            "code-search results are all valid sources when they provide concrete",
            "comment examples.",
            "",
            "Suggested searches:",
            '- `"<Language> programming language comment"`',
            '- `"<Language> programming language block comment"`',
            '- `"<Language> programming language nested comment"`',
            '- `"site:stackoverflow.com <Language> programming language comment"`',
            '- `"site:github.com <Language> programming language comment"`',
            '- `"site:sourceforge.net <Language> programming language comment"`',
            '- `"<Language> programming language <delimiter> comment"`',
            "",
            "Record representative outcomes for the reviewed unsupported-scenario",
            "probes. Do not skip a family just because it behaved correctly.",
            "",
            "## Output format",
            "",
            "For each reviewed case family, record:",
            "- the exact input",
            "- the fixture file updated, or `findings-only` if the candidate fails",
            "- the fixture case label or unique sentinel added to the file",
            "- the extraction entry point used",
            "- the sanitizer entry point used when applicable",
            "- the raw extracted match",
            "- the actual output",
            "- the expected behavior",
            "- the actual sanitized output when applicable",
            "- the expected sanitized output when applicable",
            "- the removal contract",
            "- the preservation contract",
            "- the paired preservation testcase when a symbol-removal case is kept",
            "- the source URL or provenance when the case came from the internet",
            "- the verification command and result for fixture edits",
            "- why the case matters",
            "",
            "## Assigned languages",
            "",
            render_language_scope(contexts),
        ]
    )


def render_fixer_prompt(chunk_name: str, contexts: list[LanguageContext]) -> str:
    findings_path = f"docs/comment_testing/threads/{chunk_name}_findings.md"
    resolution_path = f"docs/comment_testing/threads/{chunk_name}_resolution.md"
    return "\n".join(
        [
            f"# Fixer Packet: {chunk_name}",
            "",
            "Generated by `scripts/build_comment_test_packets.py`. Do not edit this",
            "file by hand.",
            "",
            "## Goal",
            "",
            "Consume breaker coverage and convert it into stable coverage. For",
            "confirmed failures, add regression tests first, then patch the parser,",
            "registry, or sanitizer with the smallest coherent change. For reviewed",
            "correct cases, record that no change was needed.",
            "",
            "## Ownership",
            "",
            f"- Read `{findings_path}`.",
            f"- Write resolution notes to `{resolution_path}`.",
            "- You may edit parser code, registry entries, tests, assigned fixture",
            "  files, and user-facing comment-parser docs as needed.",
            "- Do not rewrite breaker findings or other chunks.",
            "",
            "## Required workflow",
            "",
            "1. Validate each breaker case locally before changing code.",
            "2. Validate breaker fixture-file additions and keep them only when",
            "   they still parse correctly.",
            "3. Process every reviewed language and scenario family, not only the",
            "   failing ones.",
            "4. For sanitizer cases, validate both the raw extracted match and the",
            "   sanitized output before changing code.",
            "5. Add or extend tests for every confirmed bug or missing contract.",
            "6. Once a previously failing parser case is fixed, add the stable case",
            f"   to the relevant `{FIXTURE_DIR.as_posix()}/` fixture file.",
            "7. Pair every new sanitizer symbol-removal testcase with a testcase",
            "   where the same symbol is preserved when semantically meaningful.",
            "8. Patch the parser, registry, or sanitizer minimally.",
            "9. Preserve meaning-bearing punctuation and markers while removing only",
            "   syntax clutter introduced by comment notation.",
            "10. Record `no-change-needed` when the reviewed behavior is already",
            "   correct.",
            "11. If a case reflects an intentional limitation, document that instead of",
            "   forcing speculative support.",
            "12. Run `uv run pytest tests/test_comment_language_fixtures.py -q --no-cov`",
            "   whenever fixture files change.",
            "13. Run targeted tests first, then the default non-optional suite if the",
            "   change touches shared parser behavior.",
            "",
            "## Fixture acceptance rule",
            "",
            "A fixture edit is only correct if the file remains useful as a parser",
            "acceptance sample:",
            "- seeded registry comments still appear exactly once",
            "- breaker-added comments are expected to parse with current behavior",
            "- failing parser probes are recorded in findings until the fixer has",
            "  added tests or code changes that make them parse correctly",
            "",
            "## Sanitizer acceptance rule",
            "",
            "A sanitizer fix is only correct if it improves both sides of the",
            "contract:",
            "- superfluous delimiters, decorative gutters, and padding noise are removed",
            "- semantically important markers such as headings, bullets, TODO tags,",
            "  code examples, and CLI tokens still survive intact",
            "- whenever a symbol is removed in one test, a paired test proves that the",
            "  same symbol is preserved when it is meaningful",
            "",
            "## Resolution categories",
            "",
            "- `fixed-in-code`: parser or registry behavior changed.",
            "- `fixed-in-tests`: behavior was already correct, but coverage was missing.",
            "- `documented-limitation`: no code change; the case is now explicit.",
            "- `needs-policy-decision`: blocked on intended semantics.",
            "- `no-change-needed`: reviewed coverage was already correct.",
            "- `ambiguous-contract`: the reviewed case still needs an explicit policy",
            "  or sanitizer contract before code changes are safe.",
            "",
            "## Assigned languages",
            "",
            render_language_scope(contexts),
        ]
    )


def render_findings_skeleton(chunk_name: str, contexts: list[LanguageContext]) -> str:
    lines = [
        f"# Adversarial Findings: {chunk_name}",
        "",
        "Generated by `scripts/build_comment_test_packets.py`. This file is",
        "breaker-owned.",
        "",
        "## Scope",
        "",
        f"- Language count: `{len(contexts)}`",
        "- Status: `pending` until findings are recorded",
        "",
        "## Languages",
        "",
    ]
    for context in contexts:
        lines.extend(
            [
                f"### {context.language}",
                "",
                f"- Family: `{context.family_name}`",
                f"- Fixture file: `{context.fixture_path}`",
                "- Status: pending",
                "- Findings:",
                "  - Case: TODO",
                "  - Fixture edit: TODO",
                "  - Fixture parse check: TODO",
                "  - Extraction entry point: TODO",
                "  - Sanitizer entry point: TODO | n/a",
                "  - Input: TODO",
                "  - Raw extracted match: TODO",
                "  - Actual behavior: TODO",
                "  - Sanitized output: TODO | n/a",
                "  - Expected behavior: TODO",
                "  - Expected sanitized output: TODO | n/a",
                "  - Removal contract: TODO",
                "  - Preservation contract: TODO",
                "  - Paired preservation testcase: TODO",
                "  - Why it matters: TODO",
                "",
            ]
        )
    return "\n".join(lines)


def render_resolution_skeleton(chunk_name: str, contexts: list[LanguageContext]) -> str:
    lines = [
        f"# Adversarial Resolution: {chunk_name}",
        "",
        "Generated by `scripts/build_comment_test_packets.py`. This file is",
        "fixer-owned.",
        "",
        "## Resolution log",
        "",
    ]
    for context in contexts:
        lines.extend(
            [
                f"### {context.language}",
                "",
                "- Status: pending",
                "- Resolution: TODO",
                "- Fixture updates: TODO",
                "- Sanitizer notes: TODO",
                "- Paired-case coverage: TODO",
                "- Tests: TODO",
                "",
            ]
        )
    return "\n".join(lines)


def render_prompt_index(chunks: list[tuple[str, list[LanguageContext]]]) -> str:
    lines = [
        "# Comment Testing Prompt Packets",
        "",
        "Generated by `scripts/build_comment_test_packets.py`. Do not edit this",
        "file by hand.",
        "",
        "## Summary",
        "",
        f"- Chunk count: `{len(chunks)}`",
        f"- Supported language count: `{sum(len(contexts) for _, contexts in chunks)}`",
        "",
        "## Packets",
        "",
        "| Chunk | Languages | Breaker prompt | Fixer prompt | Findings | Resolution |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for chunk_name, contexts in chunks:
        lines.append(
            "| {chunk} | {count} | `{chunk}_breaker_prompt.md` | "
            "`{chunk}_fixer_prompt.md` | `{chunk}_findings.md` | "
            "`{chunk}_resolution.md` |".format(
                chunk=chunk_name,
                count=len(contexts),
            )
        )
    return "\n".join(lines)


def build_assignments(chunks: list[tuple[str, list[LanguageContext]]]) -> dict[str, object]:
    return {
        "supported_language_count": sum(len(contexts) for _, contexts in chunks),
        "chunk_count": len(chunks),
        "chunks": {
            chunk_name: [context.language for context in contexts]
            for chunk_name, contexts in chunks
        },
    }


def main() -> int:
    args = parse_args()
    contexts = build_language_contexts()
    chunks = chunk_contexts(contexts, args.chunk_count)

    write_text(
        ASSIGNMENTS_PATH,
        json.dumps(build_assignments(chunks), indent=2, sort_keys=True) + "\n",
    )

    for chunk_name, chunk_contexts_ in chunks:
        write_text(
            PROMPT_DIR / f"{chunk_name}_breaker_prompt.md",
            render_breaker_prompt(chunk_name, chunk_contexts_),
        )
        write_text(
            PROMPT_DIR / f"{chunk_name}_fixer_prompt.md",
            render_fixer_prompt(chunk_name, chunk_contexts_),
        )
        maybe_write_text(
            THREAD_DIR / f"{chunk_name}_findings.md",
            render_findings_skeleton(chunk_name, chunk_contexts_),
        )
        maybe_write_text(
            THREAD_DIR / f"{chunk_name}_resolution.md",
            render_resolution_skeleton(chunk_name, chunk_contexts_),
        )

    write_text(PROMPT_DIR / "README.md", render_prompt_index(chunks))

    print(f"Wrote {ASSIGNMENTS_PATH.relative_to(ROOT)}")
    print(f"Wrote {PROMPT_DIR.relative_to(ROOT) / 'README.md'}")
    print(f"Supported languages: {len(contexts)}")
    print(f"Chunks: {len(chunks)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
